### ISSUE TITLE
TODO: add ms-azure plugin

### ISSUE THREAD

**Issue by paragw09ckp** [danielsogl/awesome-cordova-plugins#1080]
Hi,

I have had a problem with "cordova-plugin-ms-azure-mobile-apps" plugin provided by Microsoft. After spending 3 days and going through all the forums, support, etc. I found out the issue was because I was "import"-ing a namespace from it in my Ionic 2 app. Instead of "import" when I used it in the old JavaScript fashion way (i.e. by declaring a variable for the namespace after all imports and before my actual @Component started and using that variable in the code) it worked. I was suggested to open an issue here so that the plugin can be included in Ionic Native.

It would be great if it can be added so that we can just "import" it while writing Ionic 2 app.

Thanks.

**Comment by Inoverse** [comment]
Do you have a link for this cordova plugin?

**Comment by paragw09ckp** [comment]
@Inoverse, here is the NPM link:

https://www.npmjs.com/package/cordova-plugin-ms-azure-mobile-apps

Thanks!

**Comment by fishme** [comment]
this plugin is depending on the mobile js sdk from azure. For that I found https://www.npmjs.com/package/@types/azure-mobile-apps maybe it will help to print the cordova plugin.

**Comment by Inoverse** [comment]
@paragw09ckp This plugin is not an Cordova-Plugin, so why should it be added to Ionic-Native?

**Comment by paragw09ckp** [comment]
@fishme - I was told by Microsoft Azure support that "azure-mobile-apps" is a different plugin and is used for something else. The one I am requesting here (cordova-plugin-ms-azure-mobile-apps), is a Cordova plugin specifically used by mobile apps frontend (like Ionic 2 in my case) to interact with Azure Mobile Apps Backend that they have added fairly recently. Therefore, I had to use it. 
And apparently it was not getting recognized when I was trying to "import" it in my TS files but it worked when I declared it as a global variable, JavaScript way, in my TS file. This solution was given to me by Microsoft Azure Support, specifically the group that support this particular library.

Hope this helps.

I would like to bring up here that I am new to Ionic (started directly on v2), Angular 2, Cordova and Azure Cloud services. So I might be wrong or my information might be incomplete. For all these technologies I am just following different documentation, forums and/or tutorials/videos available online.

**Comment by Inoverse** [comment]
The referenced plugin looks like a normal JavaScript library. Can't find any native code in there. Are you sure it's a native Cordova plugin?

**Comment by fishme** [comment]
Was for me also strange, but if you change the branche to login then you will find ios code. But I have no idea about this plugin.

**Comment by Inoverse** [comment]
Looks like the plugin isn't finished yet.

**Comment by fishme** [comment]
yeah, otherwise it should be in master.
