### ISSUE TITLE
Plugin Request: cordova-plugin-ad-adcolony

### ISSUE THREAD

**Issue by billygerhard** [danielsogl/awesome-cordova-plugins#1263]
There is an ionic-native plugin for AdMob, but there aren't any other ad services on it yet. This would allow native AdColony ads to be used easily with ionic-native. This service is mostly targeted towards mobile game creators, and would help game developers a lot.

https://github.com/cranberrygame/cordova-plugin-ad-adcolony

**Comment by ratson** [comment]
Disclaimer: I am the author of [cordova-plugin-admob-free](https://github.com/ratson/cordova-plugin-admob-free)

I would suggest to tell the user clearly that this plugin is not free, which it is not mention in the official README, but in code https://github.com/cranberrygame/cordova-plugin-ad-adcolony/blob/df35dfc996d81b9393d36ec45fab618bdb6442c9/src/android/AdColonyPlugin.java#L246

From [my research](https://github.com/ratson/cordova-plugin-admob-free#compare-to-other-projects), most ad plugins do ad-sharing with or without tell their users. In [some case](https://github.com/floatinghotpot/cordova-admob-pro/issues/544), user lost revenue without notice.

**Comment by ihadeed** [comment]
Thanks @ratson, I think that's a good idea. Similar to what the ng-cordova repo has: https://github.com/driftyco/ng-cordova#plugins-67

**Comment by danielsogl** [comment]
Hey @billygerhard.

I will take look into this.

**Comment by billygerhard** [comment]
@danielsogl Is there any update on this plugin yet?
