### ISSUE TITLE
Serve/Browser support for core plugins

### ISSUE THREAD

**Issue by AmitMY** [danielsogl/awesome-cordova-plugins#1302]
Currently, dialogs & spinner dialog are not supported in browser / serve mode.

So I have a method to show a dialog, which goes like this:
```
if (deviceHelper.isBrowser)
    alert(message);
else
    this.dialogs.alert(message, "Information", "Close");
```

And a more complex method for spinner dialog, which conditionally injects the spinnerDialog, or LoadingCtrl.

And to get the user's language I do:
```
if (deviceHelper.isBrowser)
    return new Promise((resolve) => resolve(navigator.language.split("-")[0]);
else
    return this.globalization.getPreferredLanguage();
```

https://ionicframework.com/docs/v2/native/action-sheet/
should use
https://ionicframework.com/docs/components/#action-sheets

https://ionicframework.com/docs/v2/native/toast/
should use
https://ionicframework.com/docs/v2/components/#toast

https://ionicframework.com/docs/v2/native/app-version/
Perhaps get that info from `config.xml`

https://ionicframework.com/docs/v2/native/clipboard/
has ways to do in browser

And so on...

I think that these functionalities, and more, should be supported in these / similar plugins that doesn't support browser, especially now that ionic is trying to bring full browser support, and that the native browser APIs are usually very simple.

It also makes it easier for the dev to simulate a live device when developing in browser, and basically has lots of good sides, with the major bad side being the fact that all of the plugins that might use ionic components, might need a peer-dependency or even an actual dependency of `ionic-angular`, but it is worth it imo

**Comment by AmitMY** [comment]
Here is an example of issues with the current mocking system: https://github.com/driftyco/ionic-native/issues/1350

Just making it more clear that this kind of system (native/browser) should be implemented.

**Comment by ihadeed** [comment]
I started something here https://github.com/ihadeed/ionic-native-browser but I haven't figured out the best way to do it yet.

**Comment by AmitMY** [comment]
@ihadeed Well, I think you are on the right track.

What do you think of conditional providers based on cordova being present or not?
If not, perhaps check the user's platform (desktop / mobile is what matters) and conditionally inject by that?

```
let providers = [];

if(window.cordova)
  providers.push(Toast);
else
  providers.push({ provide: Toast, useClass: ToastMock });

@NgModule({
  providers
})
```

**Comment by ihadeed** [comment]
I think the developer should implement that in their app. Similar to what Joshua blogged about here: https://www.joshmorony.com/automating-mocks-in-ionic-native-3-x/

**Comment by AmitMY** [comment]
@ihadeed Hmm ok, sounds completely fair.

So in general the idea is to supply mocks to all native plugins (via this repo), and then the dev can test in browser, and create whatever condition they want.

And of course, mocks need to follow the same interface...

Are we on the same page or am I off?

**Comment by ihadeed** [comment]
Well I think what this repo needs is something like https://github.com/driftyco/ng-cordova/tree/master/src/mocks

The repo I have up there should be more of an accessory that some people might prefer to have. It's more like "Ionic Hybrid" than "Ionic Native".

**Comment by AmitMY** [comment]
@ihadeed Yep, same idea, only for angular and ionic 3 (not angularjs and ionic 1)
