### ISSUE TITLE
Feature request: cordova-muse

### ISSUE THREAD

**Issue by mwiley63** [danielsogl/awesome-cordova-plugins#1422]
Hi Ionic team!  

I am curious if anyone is working on a wrapper for cordova-muse (https://github.com/mtriff/cordova-muse)?  I am working on an app using the cordova plugin but I would like to integrate it more tightly with Ionic.  

If not I'll take a closer look at the developer guide and maybe submit a pull request :)

Thank you for all the great work and plugins!  👍

**Comment by akshaydwivedi29** [comment]
@mwiley63 have you started working on it yet? I'm willing to develop the ionic native wrapper using the plugin https://github.com/mtriff/cordova-muse.I'll submit a PR , probably this weekend.
