### ISSUE TITLE
MediaPlugin audio playback error code 1 on android but ios OK

### ISSUE THREAD

**Issue by philipbrack** [danielsogl/awesome-cordova-plugins#1751]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When trying to create and play a media file packaged in the app under "assets/audio/spanish/overview.mp3",  I get a MediaError on android with message=undefined and code=1.  This code previously worked with and older version of ionic-native.

current package used: 3.12.1

**Expected behavior:**
Do not expect any error for this snippet

**Steps to reproduce:**
ionic cordova run android

**Related code:**

```javascript
// from within a controller.
this.audio = 'assets/audio/spanish/overview3.mp3';
this.file = this.mediaPlugin.create(this.audio, (update) => {
            console.log('audio update', update);
          }, (success) => {
            console.log('audio success', success);
          }, (audioError: MediaError) => {
            console.error('audio error: ' + audioError.message + ' code = ' +
              audioError.code
            )
            ;
          });
```

**package.json info:**

```json

    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@angular/animations": "4.1.3",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/geolocation": "3.12.1",
    "@ionic-native/media": "3.12.1",
    "@ionic-native/network": "3.12.1",
    "@ionic-native/photo-viewer": "3.12.1",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "3.12.1",
```

**Comment by kamilpatyk** [comment]
I have the same issue with 3.12.1 - before the update everyting worked fine

**Comment by ihadeed** [comment]
If you think this is an Ionic Native issue (which I doubt), please try the following versions of `@ionic-native/media` and let me know if your issue is fixed:
- 3.9.0
- 3.6.0
- 3.5.0

The versions above contained changes to the media plugin. None of the changes could've caused this issue though. Seems like a problem caused by the plugin.

**Comment by ghenry22** [comment]
if it's working on one platform but not the other and it's a simple mp3 file the most likely culprit is actually the path to the file you want to play as Android and iOS have quite different path structures.  

You can use the file plugin to get the native path to the file or a cdvfile: url either of which will simply return the correct path for either platform and both work with the media plugin.

Paths to access things across platforms is generally a bit of a headache in experience until you work it out.

**Comment by Agnostic** [comment]
I have the same issue on android, I have tried by using `assets/sounds/audio.wav` and `${this.file.applicationDirectory}www/assets/sounds.audio.wav` with no luck, it says `Error: 1`

**Comment by AndresDiaz1** [comment]
I had the same bug using ionic-audio plugin (https://github.com/arielfaur/ionic-audio/tree/3.0).
The error code comes from https://github.com/apache/cordova-plugin-media 

`MediaError.MEDIA_ERR_ABORTED`

I was using the ionic-audio plugin in an app page different from the 1st one; and throws the error code 1 trying to reproduce a .mp3 remote file; if I use the plugin in the 1st app page everything works fine.

To fix my problem I use the following html tag on my 1st app page, and then I can use the plugin everywhere 

`<audio-track #audioTrack></audio-track>`

I'm still don't sure yet why it solved the problem; but for me it does fix it.

**Comment by shivalipawar** [comment]
Even i'm facing the same issue whenever i try to play sound on android device it gives a error i.e. {Code:1}.
I have followed the approach mentioned by [https://www.raymondcamden.com/2014/06/23/Cordova-Media-API-Example] and checked all the permissions are correct for android. Still there's no success.
For iOS a strange thing noticed is it works for ipad but not on a iphone. 
Can anyone suggest a way out for both android and iOS as i'm urgently in need of a solution.

**Comment by alibahjat** [comment]
is there any solution for this problem native media plugin only work on ios

**Comment by danielhuggins** [comment]
Check this out: https://stackoverflow.com/questions/21244052/media-plugin-error-code-1

**Comment by lingdu0001** [comment]
I have the same error.
My version is 4.7.0.

**Comment by hardslk** [comment]
@lingdu0001 have you find solution for this?I am also facing same issue for create remote audio file with https server so its give Media aborted error.

**Comment by lingdu0001** [comment]
> @lingdu0001 have you find solution for this?I am also facing same issue for create remote audio file with https server so its give Media aborted error.
I  fixed this problem by uploading this file to the server and play it online.

**Comment by hardslk** [comment]
@lingdu0001 which file need to upload on server?
can you help me?

**Comment by lingdu0001** [comment]
> @lingdu0001 which file need to upload on server?
> can you help me?

The media file。

**Comment by hardslk** [comment]
@lingdu0001 this media file already at server side but our server is secure https so that time its not work.
its work in http.

**Comment by lingdu0001** [comment]
> @lingdu0001 this media file already at server side but our server is secure https so that time its not work.
> its work in http.

We are using https for apis, and http for media file...

**Comment by lingdu0001** [comment]
> @lingdu0001 this media file already at server side but our server is secure https so that time its not work.
> its work in http.

We are using https for apis, and http for media file...
