### ISSUE TITLE
checkFile unexpected behavior on android emulator. (FILE_NOT_FOUND)

### ISSUE THREAD

**Issue by thecog19** [danielsogl/awesome-cordova-plugins#1800]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Description and steps to reproduce**
I have a picture saving app. One of the steps the app takes is that when you take a picture it saves it localy, in this case, to file:///data/user/0/appname/cache/ 

Saving the file is no problem. The issue comes when its time to allow an user to access that file. I've written a method that is supposed to check for the file's presence before doing anything else. To do this we import the File provider. As so: 

```

import { File } from '@ionic-native/file';
```

Then we dependency inject it in the constructor

```
constructor(public file: File,
              public platform: Platform) {
        this.platform.ready().then(() => {
           this.storageDirectory = cordova.file.cacheDirectory;
     }
  }
```

So far so good! this.storageDirectory gets set just fine. The issue comes when its time to see if the file exists. i've narrowed down the issue code to the following. I've replaced the internal methods with console.logs for simplicity in reproducing the error

```
genFlie(fileName){
  return this.file.checkFile(this.storageDirectory, fileName).then(
         (res)=>{console.log(res)},
         (err)=>{console.log(err)}
  )
}
```
instead of res being true or false depending on if the file exists, which is the [expected behavior](https://ionicframework.com/docs/native/file/#checkFile), what happens is an error is raised, specifically, 1:	NOT_FOUND_ERR. Which seems to entirely defeat the point of having a checkFile function. I found [this fix](https://github.com/ionic-team/ionic-native/issues/1711) on github but it didn't actually solve anything for me

Other details, I'm using Android Studio to emulate android, specifically on the nexus 6, API 26.

**Comment by pooja-gaikwad15** [comment]
Facing the same issue.. hoping for a solution soon..

**Comment by thecog19** [comment]
One suggestion that's working for me (that someone suggested on the ionic forums)
~~~
return this.file.checkFile(this.storageDirectory, fileName).then(
    (res) => res,
    (err) => false
).then(fileExists => {
    console.log('does my file exist?', fileExists);
});
~~~

**Comment by GameAppsBD** [comment]
same problem 1:NOT_FOUND_ERR.

**Comment by Sharpkhodakarami** [comment]
Same issue here.

**Comment by Sharpkhodakarami** [comment]
@thecog19 you and someone else in other thread gave me a clue and I solved the issue:

```
var path = this.file.externalRootDirectory;
var directory = "ArghamNegarAndishe";
var fullpath = path + directory + "/";
```

Please pay attention to "/" at the end of fullpath

```
checkFile(fullpath: string, fileName: string, text: string) {
    try {
      this.file.checkFile(fullpath, fileName).then(
        res => true,
        err => false
      ).then(
        isExists => {
          if (isExists) {
            let alert = this.alertCtrl.create({
              title: '',
              message: 'file exists.',
              buttons: [

                {
                  text: 'cancel',
                  handler: param => {
                    return;
                  }
                },
                {
                  text: 'replace',
                  handler: param => {
                    this.file.removeFile(fullpath, fileName)
                      .then(res => {
                        this.writeFile(fullpath, fileName, text, false);
                      }).catch(x => {
                        // this.showMessage(JSON.stringify(x));
                      });
                  }
                },
                {
                  text: 'append',
                  handler: param => {
                    this.writeFile(fullpath, fileName, text, true);
                  }
                }
              ]
            });
            alert.present();
          }
          else {
            this.writeFile(fullpath, fileName, text, false);
          }
        });
    } catch (x) {
      this.showMessage(JSON.stringify(x));
    }
  }

writeFile(fullpath: string, fileName: string, text: string, append: boolean) {
    this.file.writeFile(fullpath, fileName, text, { 'append': append })
      .then(function (result) {
        // Success!
        this.showMessage("successfully saved!");
      }, function (err) {
        this.showMessage(JSON.stringify(err));
        // An error occured. Show a message to the user
      });
  }
```
