### ISSUE TITLE
Media events do not work always

### ISSUE THREAD

**Issue by soniyj** [danielsogl/awesome-cordova-plugins#1861]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

Media events are not always fired up after an audio file has loaded, problem persist with or without calling the release/destroy functions.

**Current behavior:**

Working sometimes

**Expected behavior:**

Working Always

**Steps to reproduce:**

Inject the plugin load a file and check the log.

**Related code:**

```
mediaFile = media.create(url);

mediaFile.onStatusUpdate.subscribe(
 status => {
   console.log('status', status);
 });

mediaFile.onError.subscribe(error => console.log('error', error));

mediaFile.onSuccess.subscribe(() => console.log('success'));
```

**Other information:**

**package.json info:**

```json

```

**Comment by pedrorckt** [comment]
I am having a lot of problems with current version of native media. Subscribing to status update does not fire at status 1, as was before, when the callback was on constructor.

Why remove second parameter of the constructor? Documentation stills shows as possible, but is not working anymore. 

NOT WORKING: `audio = media.create(url, success);`

How to fire success event and get status 1 on status update with media?

**Comment by pedrorckt** [comment]
Hi, @ihadeed, 

Thank you so much for the response on your commit [7105048b890cc351614499e0b76fb68fbaace2b2](https://github.com/ionic-team/ionic-native/commit/7105048b890cc351614499e0b76fb68fbaace2b2). Here I will detail my problem:

Expected (when you play and stop a media):
Success on create/play
Status 1
Status 2
Status 4
Success on stop

What I get:
[17:24:09]  console.log: Status 2 
[17:24:28]  console.log: Status 4 
[17:24:28]  console.log: Action is successful 

Status 1 is not being fired, and create/play success not being fired too.

When the constructor had success callback, it worked.

Thank you for your patience!

**Comment by FazioNico** [comment]
got the same issue... i'have write some here: https://github.com/ionic-team/ionic-native/issues/1886
