### ISSUE TITLE
Observables does not get triggered on MediaObject

### ISSUE THREAD

**Issue by frickt** [danielsogl/awesome-cordova-plugins#1886]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
I'm using ionic-native/media v.4.1
* Observables (onSuccess, onError, onStatusUpdate) does not get triggered
* GetDuration() function always return -1

**Expected behavior:**
Observables should get triggered and getDuration() should return the actual duration

**Steps to reproduce:**
Create a MediaObject
register a onStatusUpdate function
call play on the MediaObject.

**Related code:**

```
play(){
    const audio: MediaObject = this.media.create('assets/mp3/test.mp3');
    audio.onSuccess.subscribe(() => console.log('success'));
    audio.onError.subscribe(error => console.log('Error!', error));
    audio.onStatusUpdate.subscribe(status => console.log(status.toString()));
    console.log(audio.getDuration());
    audio.play();
  }
```
the console log is just '-1' from the getDuration.
the interesting thing is, if call the script more than 1 time, it works. So on the second execution of play(), all subscriptions are correct triggered and the right duration gets printed.

**package.json info:**

```json
    "dependencies": {
        "@angular/common": "4.3.2",
        "@angular/compiler": "4.3.2",
        "@angular/compiler-cli": "4.3.2",
        "@angular/core": "4.3.2",
        "@angular/forms": "4.3.2",
        "@angular/http": "4.3.2",
        "@angular/platform-browser": "4.3.2",
        "@angular/platform-browser-dynamic": "4.3.2",
        "@ionic-native/core": "4.1.0",
        "@ionic-native/media": "4.1.0",
        "@ionic-native/splash-screen": "4.1.0",
        "@ionic-native/status-bar": "4.1.0",
        "@ionic/storage": "2.0.1",
        "@ngx-translate/core": "^7.1.0",
        "@ngx-translate/http-loader": "^1.0.1",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-file": "^4.3.3",
        "cordova-plugin-media": "^3.0.1",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "cordova-spotify": "git+https://github.com/Festify/cordova-spotify.git",
        "es6-promise-plugin": "^4.1.0",
        "ionic-angular": "3.6.0",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.2",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.16"
    },
    "devDependencies": {
        "@ionic/app-scripts": "2.1.3",
        "@ionic/cli-plugin-cordova": "1.6.1",
        "@ionic/cli-plugin-ionic-angular": "1.4.1",
        "ionic": "3.7.0",
        "typescript": "2.4.2"
    },

```

**Comment by FazioNico** [comment]
get the same issue... :-( 
currently working on a application using this plug and can't publish it to the Apple store.
Cause sometime, app opening, runing good but no sound out and no error handling.  Can't debub to publish.

I've see if the play() function is trigger from a (click)="doPlay()" the observable onStatusUpdate is trigger 2. But noting if .play() is calling deirecly after . create()

ANy idéa is welcome ;-)

**Comment by mubasshir** [comment]
any solution?
