### ISSUE TITLE
Ionic Native Network subscribe for onConnect and onDisconnect not firing

### ISSUE THREAD

**Issue by ArtKuz** [danielsogl/awesome-cordova-plugins#1896]
**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**
I don't get events for onDisconnect and onConnect.

**Expected behavior:**
I need to receive events for onDisconnect and onConnect....

**Related code:**
```js
this.platform.ready().then(() => {
  this.network.onDisconnect().subscribe(() => {
    console.log('network was disconnected :-('); // not work
  });

  this.network.onConnect().subscribe(() => {
    console.log('network connected!'); // not work
  });

  document.addEventListener('online', () => console.log('Online!'), false); // not work

  console.log(this.network.onConnect()) // -> FromEventObservable
});
```

**Other information:**
Problem on Android and iOS.

**package.json info:**

```json
ionic-native/core : 3.14.0
ionic-native/network : 3.14.0
ionic (Ionic CLI) : 3.9.0
Cordova CLI : 7.0.1
Ionic Framework : ionic-angular 3.6.0
ios-deploy : 1.9.1
Node : v7.9.0
npm : 4.2.0
OS : macOS Sierra
Xcode : Xcode 8.3.3 Build version 8E3004b
```

**Comment by xeewi** [comment]
Same here, not fired on Android

**Comment by libelle** [comment]
I'm seeing this too, on iOS. Changing cell data on and off registers some of the time, but turning wifi on and off doesn't ever seem to register.

cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:
    cordova (Cordova CLI) : 8.0.0 
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.2.3 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
System:
    ios-deploy : 1.9.2 
    Node       : v6.10.3
    npm        : 5.8.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145

**Comment by setu1421** [comment]
I am getting the same issue in android. Removing wifi connection and again connecting with wifi doest not trigger any event.

**Comment by HudsonAfonso** [comment]
+1

**Comment by sminodonte** [comment]
+1

**Comment by jayzyaj** [comment]
+1 to this

**Comment by lmorelato** [comment]
+1

**Comment by JoeOsterfeld** [comment]
+1

**Comment by jbdoster** [comment]
+1.. Anything?
