### ISSUE TITLE
BUG: FileTransfer / Windows: Filetransfer not reporting anything

### ISSUE THREAD

**Issue by DennisSmolek** [danielsogl/awesome-cordova-plugins#1983]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
When I try to do a basic fileTransfer I don't get an error message or success. The same code on other platforms works as expected. 
```javascript
console.log('Starting download test!!');
const url = "http://fridge.kitchen.screenfeed.com/img/news/tr339gqf70v9ck87zgn97ttzsg.jpg";
const transfer = this.transfer.create();
transfer.download(url, this.file.dataDirectory + 'test.jpg').then(entry => {
    console.log('MEDIA: File downloaded!' + entry.toURL());
    console.log('MEDIA: test.jpg entry:', entry);
    entry.getMetadata(data => {
        console.log('MEDIA: test.jpg entry meta:', data);
    })
}, error => {
    console.log('MEDIA: test.jpg File download error:', error);
});

```
I get: `Starting Download Test!!` but then nothing...

If I list the files in the directory I can see the temporary files that are created but they have `size: 0`

**Expected behavior:**
To get either a success or fail message regarding the fileTransfer

**Steps to reproduce:**
Run the provided code block on windows

**Other information:**

- Platform: Windows 10 Desktop
- Ionic-Native: 3.6.1
- Ionic-Native-File-Transfer: 4.2.1
- Cordova-file-transfer: 1.6.3

**Comment by DennisSmolek** [comment]
Ok I resolved this and think there should be a note somewhere in the docs as this took 4 days of work to figure out WTF is going on.. 

`FileTransfer` is built on the `BackgroundDownloader` which is a cool class but has a few quirks, especially in debug/dev situations. 

For whatever reason it is fairly common to knock the download queue out of sync and the backgroundDownloader will start to act all wonky. 

It doesn't respond to ANY requests and doesn't throw errors. So you make a call to get all active downloads and nothing happens. You start a new download which says it worked, but you get no error or success for the file itself. You get stuck.. 

The very bottom of this guide has the solution: https://msdn.microsoft.com/en-us/library/hh700370

> When using Background Transfer during development, you may get into a situation where the internal caches of active and completed transfer operations can get out of sync. This may result in the inability to start new transfer operations or interact with existing operations and BackgroundTransferGroup objects. In some cases, attempting to interact with existing operations may trigger a crash. 

> To work around this issue, completely uninstall all versions of the app and re-deploy with the new language, architecture, culture, or capability. This can be done via the Start screen or using PowerShell and the Remove-AppxPackage cmdlet.

So, right click the app from the start bar, uninstall it, then relaunch the debugger. Boom, works like it should...

Leaving this open as I think a little note on the docs would be helpful, caused me to lose 4 days.

**Comment by FabianTe** [comment]
I can confirm this issue! But removing the app doesn't always work. Restarting my ios simulator doesn't always do the trick too.

The only thing I am certain really works is Closing the sim, closing xcode, running ```ionic cordova build ios``` and then starting the app from within xcode.

**Comment by glemiere** [comment]
Same error on iOS.
Doing the trick worked.
Weird issue.
