### ISSUE TITLE
safari-view-controller SHOW doesn't work

### ISSUE THREAD

**Issue by gregor-srdic** [danielsogl/awesome-cordova-plugins#2121]
**I'm submitting a ...** 
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I have updated @ionic-native/safari-view-controller to version 4.4.0 (also tested 4.3.1) and after I check if plugin is available with safariViewController.isAvailable (returns true) I call the **safariViewController.show** method, **nothing happens** - no error, but also no opened window.
If I replace the  safariViewController.show with window['SafariViewController'].show, it works correctly. 

**Expected behavior:**

The browser window should open.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

 @ionic-native/safari-view-controller@4.4.0
  cordova-plugin-safariviewcontroller@1.4.7
It happens both on Android (tested 5.1.1) and iOS (tested 11.1).
**Using @ionic-native/safari-view-controller@3.9.1 works.**

**Ionic info:**
**Android**
cli packages: 
    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0
global packages:
    cordova (Cordova CLI) : 7.1.0
local packages:
    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 26.1.1
    Node              : v6.11.2
    npm               : 5.5.1
    OS                : Windows 10

**iOS**
cli packages:
    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0
global packages:
    cordova (Cordova CLI) : 7.1.0 
local packages:
    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2
System:
    ios-deploy : 1.9.2 
    Node       : v6.11.2
    npm        : 5.5.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55

**Comment by timbru31** [comment]
I'm having the same issue, too. Any update on this?

**Comment by ingljo** [comment]
If not subscribing to observable on show, it will not show.

**Comment by PieterT2000** [comment]
Have you set hidden to false in the options object passed to the show function?
