### ISSUE TITLE
File type names is the same in typescript module and ionic native file plugin

### ISSUE THREAD

**Issue by airstep** [danielsogl/awesome-cordova-plugins#2122]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
So, how to use and separate File from typescript and File constructor from plugin. Bcz now code going throght File contructor from plugin but I need to go throught typescript dom type....

**Expected behavior:**
Expected to use File constructor from typescript

**Steps to reproduce:**
Use native file plugin and in separate provider typescript File constructor

**Related code:**

```
const file = new File([blob], filename);
```

**Other information:**
#1460 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

System:

    Node : v8.8.1
    npm  : 5.5.1 
    OS   : Linux 4.13

Misc:

    backend : pro

```

**Comment by ihadeed** [comment]
Are you importing `File` from `@ionic-native/file`? 

If you don't import anything, it should use the dom library's File interface.

**Comment by airstep** [comment]
Yep, I'm importing File from @ionic-native/file in other sample.ts file, and don't import it in service/provider (provider.ts)... But code in provider going to @ionic-native/file constructor.... But I need constructor from typescript

**Comment by airstep** [comment]
So, this is critical in use in one project. Because js didn't know correct way which class to use in one situation and which in other.... Maybe we can separate this somehow?

**Comment by ihadeed** [comment]
Sounds like an issue with webpack.. it's assuming that your other reference to `File` is from Ionic Native as well. 

You can use `window.File` but I don't think that will work since the file plugin overrides the global `File` variable.

Out of curiosity, why are you trying to use the native File class/interface while using the native plugin?

**Comment by airstep** [comment]
Thank you for reply. My webpack is there [webpack.config.zip](https://github.com/ionic-team/ionic-native/files/1485837/webpack.config.zip)

My project almost based on this [sample](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp)

And I just add new functionality and wanna to extend some posibilities

**Comment by airstep** [comment]
So , just to support many platforms like browser and devices I need to use File\typescript for browser and File\native for other platforms. Can it be real?

**Comment by hgeorgilas** [comment]
Is there any update on this issue? I'm facing the exact same issue
