### ISSUE TITLE
@ionic-native/calendar requestWritePermission don't trigger on then after the response user

### ISSUE THREAD

**Issue by lucascco** [danielsogl/awesome-cordova-plugins#2140]
**I'm submitting a ...**
[X ] bug report

**Current behavior:**
When I call on method (requestWritePermission or requestReadWritePermission), the prompt shows up but the *then* isn't triggered by the action user.

**Expected behavior:**
After the user answered, the then on Promise from the methods (requestWritePermission or requestReadWritePermission) should be triggered.

**Related code:**

```
  private _hasPermission() {
    return this.calendar.hasReadWritePermission()
      .then(res => {
        console.log('_hasWritePermission', res);
        if (!res) {
          return this.calendar.requestReadWritePermission(); // **Don't trigger anything**
        } else {
          return res;
        }
      })
      .catch(error => {throw error;});
  }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/lucas/Projetos/Liga/liga-app/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v8.4.0
    npm  : 5.5.1 
    OS   : Linux 4.10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

```

I called createEvent() directly without check permissions, seems resolved, but I think this is an issue that should be seen.

Thanks =)

**Comment by Artfloriani** [comment]
I had the same issue on Android (8.0) but iOS worked fine here.

**Comment by AlexDZI** [comment]
+1
Same issuer Android 6 / Ionic 3
