### ISSUE TITLE
ionic build failed of cordova-plugin-file-tranfer was added

### ISSUE THREAD

**Issue by zengyufang** [danielsogl/awesome-cordova-plugins#2170]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```
![image](https://user-images.githubusercontent.com/23447639/33538354-dbde4452-d8fb-11e7-8a32-565d424f8b6a.png)
before add cordova-plugin-file-tranfer, build apk is success,but after add this plugin,build falied, I don't know why build failed?I need help ,thanks.
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by NoNameProvided** [comment]
You don't need to use the file-transfer plugin anymore, you can use browser API to archieve the same result. Check the [deprecation notice](https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html) for details.

**Comment by zengyufang** [comment]
okay,but I use Browser API ,and follow the documentation，An error in the
![image](https://user-images.githubusercontent.com/23447639/33541313-ac45c432-d909-11e7-843a-262f283ebb87.png)

**Comment by SMTaha** [comment]
@zengyufang Did you solved this issue? I am also facing the same issue.
