### ISSUE TITLE
Do not promote plugins which are deprecated or replaceable by web apis

### ISSUE THREAD

**Issue by NoNameProvided** [danielsogl/awesome-cordova-plugins#2171]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
Some of the plugins wrapped by ionic-native are replaceable by standardized easy to use plugins.
While these plugins are needed for supporting older systems, I think it's important to show the developers that alternatives exist. So I propose two thing: 

**Expected behavior:**
1. Show links to articles or MDN pages when some functionality is achievable by web APIs.
2. Show deprecation warning for core plugins when they are sunsetted by the Cordova foundation. (An example is the [file-transfer-plugin](https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html))

**Comment by Remco75** [comment]
Do you have a list of plugins already?
We could make a PR with these changes

**Comment by NoNameProvided** [comment]
Not yet. Will do a quick check on the weekend.
