### ISSUE TITLE
Set event as all day in Calendar

### ISSUE THREAD

**Issue by ghost** [danielsogl/awesome-cordova-plugins#2201]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently there's no way to set `all_day` flag while creating an `Event` in `Calendar`

**Expected behavior:**
There should be a boolean parameter to set `all_day` flag while creating an `Event` in `Calendar`

**Steps to reproduce:**

**Related code:**

```
    /**
     * Silently create an event with additional options.
     *
     * @param {string} [title]  The event title
     * @param {string} [location]  The event location
     * @param {string} [notes]  The event notes
     * @param {Date} [startDate]  The event start date
     * @param {Date} [endDate]  The event end date
     * @param {CalendarOptions} [options]  Additional options, see `getCalendarOptions`
     * @returns {Promise<any>} Returns a Promise
     */
    createEventWithOptions(title?: string, location?: string, notes?: string, startDate?: Date, endDate?: Date, options?: CalendarOptions): Promise<any>;

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    cli packages: (/usr/local/lib/node_modules)

        @ionic/cli-utils  : 1.19.0
        ionic (Ionic CLI) : 3.19.0

    global packages:

        cordova (Cordova CLI) : 7.1.0

    local packages:

        @ionic/app-scripts : 3.1.2
        Cordova Platforms  : android 6.3.0
        Ionic Framework    : ionic-angular 3.9.2

    System:

        Android SDK Tools : 26.1.1
        Node              : v9.2.0
        npm               : 5.5.1
        OS                : Linux 4.4

    Environment Variables:

        ANDROID_HOME : /home/serpentcs/Android/Sdk

    Misc:

        backend : pro

```

**Comment by codinronan** [comment]
@KasimSCS Darn, I wish I had seen this earlier; yes this can be done, the field is just missing in the Ionic Native typescript definition. When you get the calendar options:

`const options = this.calendar.getCalendarOptions();`

You can then just do:

`options['allday'] = true;`

And that will have the desired effect.
