### ISSUE TITLE
fcm onNotification() only triggers one subscription

### ISSUE THREAD

**Issue by mzealey** [danielsogl/awesome-cordova-plugins#2207]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

```
        platform.ready().then( () => {
                this.fcm.onNotification()
                    .subscribe( data => ... )
        })
```

When I do this in one location (eg a service or app) it works fine. When I do 2 subscriptions like this from different places, I only get the first one triggering the other is ignored. As I understand it, an `Observable` like this should trigger all subscribes.

**Comment by telran** [comment]
If you look at the code from the plugin every time you call onNotification the method overwritten by fcm is called.

Workaround: You can write a service that provides e.g. a BehaviorSubject and subscribe to onNotification. Your code can now listen multiple times to the BevaviorSubject and you have only one subscription to onNotification.

**Comment by AlexisCaffa** [comment]
If it is not a bug, it is a design issue (although not very intuitive).

Another solution could be:
``` TypeScript
const obs: Observable<any> =  this.fcm.onNotification().share();

obs.subscribe( data => ... );

return obs
```
