### ISSUE TITLE
Httpd: plugin_not_installed 

### ISSUE THREAD

**Issue by khoshrou** [danielsogl/awesome-cordova-plugins#2241]
**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
Httpd component always raises plugin_not_installed
plugin have been installed but i still get this error

**Expected behavior:**
should work normally

**Steps to reproduce:**
create a blank ionic app, install httpd plugin as described in the ionic document
run the following code in a button click event

**Related code:**

startServer(wwwroot)
	{
		let str = "1";

		try
		{
			if (this.httpd)
			{
				str += "-2";
				// before start, check whether its up or not
				this.httpd.getUrl().then(url =>
				{
					str += "-3";
					if (url.length > 0)
					{
						str += "-4";
						alert("server is up: <a href='" + url + "' target='_blank'>" + url + "</a>");
					}
					else
					{
						str += "-5";
						
						let options: HttpdOptions = {
							www_root: wwwroot, // relative path to app's www directory
							port: 80,
							localhost_only: true
						};

						this.httpd.startServer(options).subscribe((data) =>
						{
							str += "-6";
							alert('Server is live');
						});
						str += "-7";
						alert('Server 2');
					}

				}).catch(e =>
				{
					str += "-8";
					alert(e);
				});
			}
			else
			{
				str += "-9";
				alert('CorHttpd plugin not available/ready.');
			}
		} catch (e)
		{
			str += "-10";
			alert(e);
		}

		alert(str);
		
	}

**Ionic info:**

cli packages: 

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

local packages:

    @ionic/app-scripts : 3.1.7
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.10.0
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : legacy

**Comment by mebibou** [comment]
On which platform are you trying this?

**Comment by khoshrou** [comment]
both android and ios, if I use plugins api its working but ionic native raises "plugin_not_installed"

**Comment by devilop3rz** [comment]
I get the same Issue on Android (not tested iOS). Tried to install the plugin via npm & directly from git.

**Comment by colossatr0n** [comment]
I'm having this issue as well with httpd. I read up on this [solution](https://forum.ionicframework.com/t/ionic-native-httpd-plugin-the-httpd-plugin-is-not-installed/170741). I'm not using DevApp though, I'm using the IOS emulator, so I'm not sure what the issue is.
