### ISSUE TITLE
Onesignal handleNotificationOpened breaks angular change detection

### ISSUE THREAD

**Issue by gerits** [danielsogl/awesome-cordova-plugins#2269]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When resuming an application (opened before, but moved to background) via a push notification the angular change detection does not work anymore.

**Expected behavior:**
Angular change detections remains working.

**Steps to reproduce:**
1. Open application.
2. Move application to background (press home button)
3. Receive push notification
4. Open application via push notifications
5. Navigate to another page in handleNotificationOpened
6. Interact with page (button click that updates value)

**Related code:**

app.component.ts
```
this.platform.ready().then(() => {
    this.oneSignal.startInit('appId', 'googleProjectNumber');
    this.oneSignal.inFocusDisplaying(OSDisplayType.None);
    this.oneSignal.handleNotificationOpened().subscribe((pushData) => {
        this.navCtrl.setPages({
            {
                page: RootPage,
            },
            {
                page: SubPage,
            }
        });
    });
    this.oneSignal.endInit();
}
```

**Other information:**
I used a workaround for now by invoking setPages inside a ngZone.run() as in example below.

app.component.ts
```
this.platform.ready().then(() => {
    this.oneSignal.startInit('appId', 'googleProjectNumber');
    this.oneSignal.inFocusDisplaying(OSDisplayType.None);
    this.oneSignal.handleNotificationOpened().subscribe((pushData) => {
        this.ngZone.run(() => {
            this.navCtrl.setPages({
                {
                    page: RootPage,
                },
                {
                    page: SubPage,
                }
            });
        });
    });
    this.oneSignal.endInit();
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
▶ ionic info
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v6.12.2
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/rubengerits/Library/Android/sdk

Misc:

    backend : pro
```

Ionic native version: ```"@ionic-native/onesignal": "4.5.2",```

**Comment by sadqainsixlogs** [comment]
do you get a successful workaround?
