### ISSUE TITLE
Remove Confirmation button for the ionic-camera plugin

### ISSUE THREAD

**Issue by greg-devtac** [danielsogl/awesome-cordova-plugins#2295]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Confirmation dialog is showing in the camera plugin

**Expected behavior:**
Confirmation dialog in the camera should show instead it will automaticaly get the base64 data

**Steps to reproduce:**

**Related code:**

```
let options: CameraOptions = {
			quality: 100,
			destinationType: this.camera.DestinationType.DATA_URL,
			encodingType: this.camera.EncodingType.JPEG,
			mediaType: this.camera.MediaType.PICTURE,
			correctOrientation: true,
			targetWidth: 1024,
			targetHeight: 768,
			saveToPhotoAlbum: false
		};

		this.camera.getPicture(options).then((imageData) => {
			let loading = this.loading.create({
				content: 'Optimising Image from Camera ...'
			});
			loading.present();
			setTimeout(() => {
				loading.dismissAll();
				this.takePicture(imageData);
			}, 4000)
		}, err => {
			this.close(0);
			console.log(err);
		})
```

**Other information:**
I would like to remove the confirmation dialog the Retry and ok Button instead of showing that button it should redirect to my application after i click the capture button.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\Gregorio\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v6.11.0
    npm  : 2.15.12
    OS   : Windows 7

Misc:

    backend : pro
```

**Comment by victorwpbastos** [comment]
Any progress on this?

**Comment by ketanakbari** [comment]
Is there any progress on this?

**Comment by dex252** [comment]
Has anyone solved this?
