### ISSUE TITLE
Upload mutiple images in filetransfer

### ISSUE THREAD

**Issue by chiragebiztrait4** [danielsogl/awesome-cordova-plugins#2298]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Hello ionic team, 
I am developing apps in ionic from last 1 year.
In one project, i need to upload multile images via file-transfer. i am having no issue while uploading single image,

firstly, filetransfer plugin not accepting array of images to upload, i tried uploading one-by-one image in while loop, that is not a proper way of achieving that but this thing does work wrong when you are performing actions like add product.

So can you give me proper way of uploading multiple images from file-transfer

**Expected behavior:**
There must be way of uploading multiple images from plugin

**Steps to reproduce:**
* create new project by using ionic-starter,
* build a form with 4-5 input fields, and one button to choose image from gallery, display it and upload to server

**Related code:**

```
this.path = imageData;
 let options1: FileUploadOptions = {
            params: this.params,
            fileKey: 'path',
            fileName: imageName,
            mimeType: "image/png,image/jpeg"
          }
          var upload = fileTransfer.upload(this.path, encodeURI(this.globals.SERVER_URL + 'addMarketingAd'), options1).then((data) => {
            let uploadRes = JSON.parse(data.response);

            this.loaderProvider.hide();
            if (uploadRes.status) {
              this.openWebView(uploadRes);
              const toast = this.toast.create({
                message: "Ad successfully uploaded, it will disable after 24 Hour",
                duration: 3000,
                position: 'bottom'
              });
              toast.present();
            } else {
              const toast = this.toast.create({
                message: "Cannot upload this image",
                duration: 3000,
                position: 'bottom'
              });
              toast.present();
            }

          }, (err) => {
            let msg = "Cannot upload this image";
            if (err.code == 1) {
              msg = "Cannot find uploaded file, try again";
            } else if (err.code == 2) {
              msg = "Invalid url";
            } else if (err.code == 3) {
              msg = "Please check your connection and try again";
            } else {
              msg = "Unable to upload image, try again";
            }

            this.loaderProvider.hide();
            const toast = this.toast.create({
              message: msg,
              duration: 3000,
              position: 'bottom'
            });
            toast.present();
          });
```

**Other information:**

* [https://forum.ionicframework.com/t/multiple-image-uploads-with-ionic/114955](ionic forum link)
* [https://forum.ionicframework.com/t/upload-multiple-images-using-filetransfer-upload/116107](ionic forum link 2)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: 

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.3
    npm  : 5.5.1
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by ravikumar007vision** [comment]
Convert images into base64 and push them into array and use https method to upload . In backend convert back to get all images. like
let postPayloadData= {
                      info : this.info,   //title,description
                      imagePayLoad:this.imageArray
                    };

    this.restProvider.newsPost(postPayloadData)
      .then(data => {
        console.log(data);
       //response
      });

**Comment by ravikumar007vision** [comment]
Convert images into base64 and push them into array and use https method to upload . In backend convert back to get all images. like

let postPayloadData= {
info : this.info, //title,description
imagePayLoad:this.imageArray
};

this.restProvider.newsPost(postPayloadData)
  .then(data => {
    console.log(data);
   //response
  });
