### ISSUE TITLE
StatusBar backgroundColorByHexString not applied in a prod build

### ISSUE THREAD

**Issue by Iyashu5040** [danielsogl/awesome-cordova-plugins#2307]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm using the StatusBar plugin to change the color of the status bar in an Android app. I'm waiting for platform ready to be completed before setting the color. When I run the app with `ionic cordova run android` the status bar changes color as intended. When I add the `--prod` parameter the status bar just stays the default blue.

**Expected behavior:**
The status bar color needs to change regardless of whether it's a debug or prod build.

**Related code:**

```
this.statusBar.backgroundColorByHexString("#2f2e33");
```

**Other information:**
package.json:
"ionic-native/core": "4.5.3",
"ionic-native/status-bar": "4.5.3",
"cordova-plugin-statusbar": "^2.4.1"

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/jacquesnieuwoudt/Desktop/Projects/1Fetch/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.5.1
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2 
    Node       : v6.11.5
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by luizmacfilho** [comment]
Same problem here

**Comment by marutifh** [comment]
Hi, Any update on this?

**Comment by JRR-OSU** [comment]
@marutifh This bug is still present.

**Comment by dylanvdmerwe** [comment]
Check the `theme-color` in the index.html file if using Crosswalk.

**Comment by killian2301** [comment]
Same here... Any updates about this issue?

**Comment by Paul-Etienne** [comment]
Hi, I had the same issue happening to me with the "--prod" flag.
I was able to fix it by moving the code `this.statusBar.backgroundColorByHexString("#2f2e33");` from the app constructor to the `platform.ready()` callback.

Basically, my app.component.ts now looks like this :
```
constructor(public platform: Platform, 
            public statusBar: StatusBar,
            ...) {
    this.initializeApp();
}

private initializeApp() {
    this.platform.ready().then(() => {
        this.statusBar.backgroundColorByHexString("#2f2e33");
      }
...
}
```

Hoping this will help someone.

**Comment by prabhashibuddhima** [comment]
Hi, 

I'm having the same issue. It's working fine in the android devices. but not working in iOS,

**Comment by nachibat** [comment]
Hi, any update of this issue?
