### ISSUE TITLE
Ionic Native - Network onchange() works incorrectly ios

### ISSUE THREAD

**Issue by lordsteggu** [danielsogl/awesome-cordova-plugins#2317]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
The issue is prevalent on ios only, I have created implemented a static global onChange().subscribe.
From this I am checking whether network is 4g, 3g or wifi and perform certain actions accordingly.

However on ios, the onChange is called before the actual value of the network information is updated, so when I go from having wifi to not having wifi, the change event is called, will say I still have wifi because it has not updated, if I turn it back on, it will say I have no wifi, but I do. 

It is always out of sync.

This does not happen on android, it works as expected on android

Here is a demo repo for you to test the issue https://github.com/lordsteggu/NetworkTest

**Expected behavior:**
The ios  network change event is called before the network value has updated 

**Steps to reproduce:**
Install the repo above on both ios and android
once installed turn on and off the network - both 4g wifi etc... 
there is an alert that informs you of the state of the network
this is using - this.network.type to check the network states

Ionic Info

```
 @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.4.0
    npm  : 5.5.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro 
```

Package JSON
```
{
  "name": "NetworkTest",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/network": "^4.5.3",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/storage": "2.1.3",
    "cordova-android": "6.3.0",
    "cordova-plugin-device": "^2.0.1",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.8",
    "typescript": "2.4.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-network-information": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {}
    },
    "platforms": [
      "android"
    ]
  }
}
```

**Comment by oal** [comment]
We have this problem as well.

The network events seem to be firing incorrectly especially as the app is starting up / right after loading. As a workaround, we added a 500ms delay after platform.ready before doing anything, or subscribing / using any information from the network provider, and this seems to have helped.
