### ISSUE TITLE
 Can’t get gallery image with url

### ISSUE THREAD

**Issue by minareth** [danielsogl/awesome-cordova-plugins#2318]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

Hello. I’m trying to prepare image for sending to the server from gallery or camera. Started with gallery. Using cordova-plugin-camera. I’m getting an image URL like 
content://media/external/images/media/27494/

when I use it in img src="{{URL}}"

I get broken-link icon , or grey background in case if ion-img

`<<HTML>>
<ion-content padding>
  \<img style="width: 200px; height: 60px;" *ngIf="lastImage" src={{lastImage}}>

 \<ion-img style="width: 200px; height: 60px;" *ngIf="lastImage" src={{lastImage}}></ion-img>

  \<img style="width: 200px; height: 60px;" *ngIf="lastImage" src="content://media/external/images/media/27494/">

  \<ion-img style="width: 200px; height: 60px;" *ngIf="lastImage" src="content://media/external/images/media/27494/"></ion-img>

  \<div style="width: 200px; height: 60px;" [style.background-image]="'url(' + lastImage + ')'"></div>

  \<img style="width: 200px; height: 60px;" *ngIf="lastImage" src={{lastImageNotSanitized}}>

  \<div style="width: 200px; height: 60px;" [style.background-image]="'url(' + lastImageNotSanitized + ')'"></div>

  \<ion-img style="width: 200px; height: 60px;" *ngIf="lastImage" src={{lastImageNotSanitized}}></ion-img>

  \<img style="width: 200px; height: 60px;" *ngIf="lastImage" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
    9TXL0Y4OHwAAAABJRU5ErkJggg==">

  \<div class="">{{lastImage}}</div>

  \<div class="">"{{lastImage}}"</div>

  \<h3 *ngIf="!lastImage">Please Select `Image!</h3>

</ion-content>

<<.ts>>
  options: CameraOptions = {
    quality: 50,
    destinationType: 2,
    encodingType: this.camera.EncodingType.JPEG,
    mediaType: this.camera.MediaType.PICTURE,
    sourceType: 0,
  };
  public presentActionSheet() {
    let actionSheet = this.actionSheetCtrl.create({
      title: 'Select Image Source',
      buttons: [
        {
          text: 'Load from Library',
          handler: () => {
            this.camera.getPicture(this.options).then((imageData) => {
                  this.lastImage = this.sanitizer.bypassSecurityTrustUrl(imageData);
                  this.lastImageNotSanitized = imageData;
            }, (err) => {
              this.presentToast('Error.');
            });
          }
          },
        {
          text: 'Cancel',
          role: 'cancel'
        }
      ]
    });
    actionSheet.present();
  }
`

**Expected behavior:**

<img style="width: 200px; height: 60px;" *ngIf="lastImage" src="content://media/external/images/media/27494/">
  <ion-img style="width: 200px; height: 60px;" *ngIf="lastImage" src="content://media/external/images/media/27494/"></ion-img>

those should show images, not broken link icons

**Steps to reproduce:**

code is above, I'm using ionic view application on meizu 5, android 6.0

**Related code:**
![s80206-14200892](https://user-images.githubusercontent.com/16062830/35859984-f079e8fe-0b4a-11e8-9303-7c61738013f0.jpg)

code is above
```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here

cli packages: (C:\Users\User\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.4.0
    npm  : 5.3.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by danielsogl** [comment]
Please format your issue code

**Comment by sizvix** [comment]
Same bug here, sometines, the module return a "content://" path and not a "file://"

- Take photo : OK "file://..."
- Get Image from photo library :
  - get resized image (with targetWidth/Height) : OK "file://..."
  - get image from screenshot : OK "file://..."
  - get PNG when we ask for JPEG : OK "file://..."
  - get JPEG when we ask for JPEG : KO "content://..."
