### ISSUE TITLE
Naming conventions create name collisions, confusion, bugs

### ISSUE THREAD

**Issue by roblouie** [danielsogl/awesome-cordova-plugins#2369]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Everything in Ionic Native is an Angular Service that must be provided, however, none of them are named with the Service suffix as suggested by Angular best practices. While this itself is only minorly confusing, the very generic names (Camera, File) lead to extreme confusion. There is already a type 'File', it's returned in a FileList by a file input, and used by the FileSystem API, which the Cordova File plugin is modeled after.

So, importing your File service causes a very confusing naming collision with the native File type. Furthering this confusion, the methods in your File service that deal with the actual native File object return IFile, an interface you created that is identical to the native File object...

**Expected behavior:**
Give Ionic Native services proper names that don't represent simple models. Something specific like IonicFileService would be ideal. Make your plugins deal with the built in native types whenever possible, so don't declare your own made up IFile interface, simply return the native File type.

**Steps to reproduce:**
Simply import File from IonicNative into your app anywhere you are also trying to work with the native File object.

**Related code:**

```
// This shouldn't be required of your users, but it's the only valid way to use the service presently
import { File as IonicFileService } from '@ionic-native/file';
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\liqui\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 6.5.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

```

**Comment by danielsogl** [comment]
I would prefer the name PluginNamePlugin rather than PluginNamenService.

What do you think about this @ihadeed?
