### ISSUE TITLE
cordova-plugin-app-version does not work on IOS with 0.1.9 please add working versions to the docs

### ISSUE THREAD

**Issue by badpenguin** [danielsogl/awesome-cordova-plugins#2371]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[X] feature request

**Current behavior:**
Under IOS cordova-plugin-app-version 0.1.9 is reported as not installed, luckly 0.1.8 still works.

**Expected behavior:**
Plugin is installed and reports correctly the version number.

**Steps to reproduce:**
Compile under IOS with version 0.1.9 of  cordova-plugin-app-version

**Other information:**
Please also add to the "ionic native" documentation the matching version of the cordova plugin that is  required to work: is an headache to keep things in sync.

**Comment by danielsogl** [comment]
Hey,

I cannot reproduce this kind of error on iOS with the latest plugin release.
