### ISSUE TITLE
Native plugin for the `cordova-plugin-scanbot-sdk`

### ISSUE THREAD

**Issue by Sampath-Lokuge** [danielsogl/awesome-cordova-plugins#2411]
[X ] feature request

Could we have Ionic native plugin for the `cordova-plugin-scanbot-sdk`?

https://www.npmjs.com/package/cordova-plugin-scanbot-sdk 

https://scanbot.io/en/sdk.html

**Comment by Sampath-Lokuge** [comment]
Thanks a lot for the accepting the request :+1:  @danielsogl

**Comment by ihadeed** [comment]
Is this plugin even popular? hard to find data since it's a paid plugin with no public code & low download count.

**Comment by Sampath-Lokuge** [comment]
That is true. But we don't have any scanning and document creation plugin for Ionic at the moment. Hence we would like to have at least paid one. Thanks. @ihadeed
