### ISSUE TITLE
LocalNotification.fireQueuedEvents() doesn't work

### ISSUE THREAD

**Issue by mkoorevaar** [danielsogl/awesome-cordova-plugins#2498]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When calling LocalNotification.fireQueuedEvents() within the platform.ready() in order to fire the triggered notification when the app was closed, shows an error that the ionic-cordova-local-notification wasn't installed. When the app is running or in background the LocalNotification doesn't give any problems.

**Expected behavior:**
perform the fireQueuedEvents() on the ionic-cordova-local-notification plugin.

**Steps to reproduce:**
- @ionic-native/local-notification 4.7.0
- ionic-cordova-local-notification 0.9.0-beta2
- android 6.4.0

**Related code:**

```
insert any relevant code here
```

**Other information:**
It looks like this and more methods aren't transferred correctly from the ionic-native plugin to the native cordova plugin.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jrista** [comment]
I believe it is because you are using ionic-cordova-local-notification 0.9.0 beta. According to their github page, 0.9.x is not supported by Ionic Native yet.

**Comment by Leobaillard** [comment]
I'm encountering the same problem.

**Ionic info**
```% ionic info 

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 7.0.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 6.3.0 
    OS   : Linux 4.18
```

Using:
- @ionic-native/local-notifications: ^4.12.2
- cordova-plugin-local-notification: ^0.9.0-beta.2

I'm running the app on a real device with `ionic cordova run android --device`. I tried with and without the `-l` option and I'm not using `-c`

**Comment by CapotR** [comment]
I had the same issue.

Installing "cordova-plugin-local-notification@0.9.0-beta.3" fixed it on IOS

**Comment by jrista** [comment]
Aye, using Beta 3 resolved it for me as well.
