### ISSUE TITLE
Base64 to Gallery in ios through error `plugin_not_installed 

### ISSUE THREAD

**Issue by gopi2mohan** [danielsogl/awesome-cordova-plugins#2516]
**Current behavior:**
Not able to save the image to galary in ios platform

**Expected behavior:**
   To save the base64 string to gallery.

**Steps to reproduce:**
Click on a button invoke the plugin through's error callback of `plugin_not_found` But in android everything works fine as expected.

**Related code:**

[let options:Base64ToGalleryOptions = { prefix: '_img',mediaScanner: true };

    this.platform.ready().then(() => {

      this.base64ToGallery.base64ToGallery(base64Image,options)
      .then(
        res => {
          debugger
          console.log('Saved image to gallery ', res);
        },
        err => {
          debugger
          console.log('Error saving image to gallery ', err);
        });

    })]

**Other information:**
https://stackoverflow.com/questions/50268958/ionic3-base64-to-gallery-plugin-crashes-the-app

https://forum.ionicframework.com/t/ionic-native-base64-to-gallery-doesnt-work/51852

**Comment by jratiwanich** [comment]
I'm getting the same error on iOS. Did anyone find a solution for this?
