### ISSUE TITLE
@ionic-native/contacts on iOS 11

### ISSUE THREAD

**Issue by ChrisHuntCal** [danielsogl/awesome-cordova-plugins#2595]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
The combination of cordova-plugin-contacts and @ionic-native/contacts as described in the ionic native docs is not working on iOS 11 using a clean install of ionic via "ionic start".  A PLUGIN_NOT_INSTALLED error is thrown.  This can be resolved however by including the cordova-plugin-ios-contacts-permissions plugin into the project.

**Expected behavior:**
Following the ionic native docs to include contact list functionality should be complete, and result in working functionality.

**Steps to reproduce:**
Create a new project using "ionic start", install the cordova-plugin-contacts and the @ionic-native/contacts library.  On platform.ready, attempt to perform a search via contacts.find() using a device running iOS 11.

**Other information:**
We should update the ionic native docs.

**Comment by danielsogl** [comment]
The contacts plugin is deprecated. Maybe thats the problem: https://github.com/apache/cordova-plugin-contacts#deprecation-notice

But also check out the iOS guide here: https://github.com/apache/cordova-plugin-contacts#ios-quirks

**Comment by Jadeng24** [comment]
Can you show me your repository? im trying to get ionic-native/contacts to work in my ionic native mobile app but isn't letting me.

**Comment by Dineshrajaa** [comment]
still the issue persist in plugin version **5.0.0-beta.21**, is there anyway to get rid of this and get the app bundled?
