### ISSUE TITLE
Streaming Media Stop Video

### ISSUE THREAD

**Issue by Saqib92** [danielsogl/awesome-cordova-plugins#3232]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
No Stop Video Functionality for cordova-plugin-streaming-media plugin.

**Expected behavior:**
There should be a stop / Close video Functionality for Streaming media Plugin. 
**Steps to reproduce:**

Create Project,
Install streaming media Plugin

**Related code:**
it should be like:
`this.streamingMedia.stopVideo(); // to close media player programmatically`
**Other information:**

[Issue created with Plugin Repo](https://github.com/nchutchind/cordova-plugin-streaming-media/issues/205)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
Ionic:

   Ionic CLI                     : 5.2.1 (C:\Users\ammar\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.2
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:

   cordova-res : 0.5.1
   native-run  : 0.2.7

System:

   Android SDK Tools : 26.1.1 (C:\Users\ammar\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.11.3
   OS                : Windows 10

**Comment by Saqib92** [comment]
Any updates?

**Comment by danielsogl** [comment]
@Saqib92  You have to add any plugin by yourself to the repository since this repo is driven by the community itself and not by the ionic-team.
