### ISSUE TITLE
@ionic-native/device-orientation watchHeading does not clear the interval/timer when unsubscribed and keeps on making native calls to get compass heading details forever 

### ISSUE THREAD

**Issue by ryaa** [danielsogl/awesome-cordova-plugins#3537]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

When watchHeading method on DeviceOrientation plugin (https://ionicframework.com/docs/native/device-orientation) is invoked and then unsubscribed the timer is not cleared and the app still making calls to native layer to get compass heading details. Please note that further calls to watchHeading set more intervals to make periodic calls to native code to get compass heading data which is never cleared.

**Expected behavior:**

Unsubscribe must clear the timer correctly and stop making calls into native code to get compass heading data.

**Steps to reproduce:**

1) Check out the repo [ionic-native-device-orientation-watch-heading-bug](https://github.com/ryaa/ionic-native-device-orientation-watch-heading-bug), then build and run the app.
2) Tap on Watch Heading button
Note that there will be compass heading data logged into console
3) Tap Stop Watching Heading button
Note that there will be NO compass heading data logged into console however the timer is not cleared and the app still making calls into the native code to get compass heading data.

The problem is that the cordova plugin clearWatch method is invoked with id param undefined which does not clear the interval set in watchHeading method - see below
<img width="1604" alt="Screenshot 2020-09-16 at 16 32 55" src="https://user-images.githubusercontent.com/3608222/93346726-f1ff7b80-f83c-11ea-9fd5-95b5b781a9e6.png">

You can set the break point as below and see that the interval still invokes getCurrentHeading method periodically
<img width="1613" alt="Screenshot 2020-09-16 at 16 22 22" src="https://user-images.githubusercontent.com/3608222/93346818-0c395980-f83d-11ea-9a81-8947a846a466.png">

which translates into a subsequent call into the native code - see below
<img width="1556" alt="Screenshot 2020-09-16 at 16 36 43" src="https://user-images.githubusercontent.com/3608222/93346863-19eedf00-f83d-11ea-800e-7ba598819b00.png">

It seems that this will never be cleared until the app is terminated.

**Comment by rmallermartins** [comment]
Having the same issue, any updates about this?

**Comment by neonish** [comment]
Having the same issue, any updates about this?

**Comment by biancaaaaa** [comment]
Having the same issue, looking forward to updates here 😅

**Comment by gelinger777** [comment]
has anybody found a solution?

**Comment by mouroutd** [comment]
For me the issue still exists.

To resolve this I have made a custom subscription event (you can set a javascript interval) which uses the DeviceOrientation.getCurrentHeading() with 50ms timeout to do my bidding and afterwards I unsubscribe from that.

**Comment by ryaa** [comment]
> has anybody found a solution?

I have created the compass utils provider with the below method allowing to unsubscribe as needed
```
    /**
     * Watch the device compass heading change
     */
    public watchCompassHeading(frequency: number): Observable<{ magneticHeading: number; trueHeading: number; headingAccuracy: number; timestamp: number }> {

        const observable = new Observable<DeviceOrientationCompassHeading>((subscriber) => {

            // eslint-disable-next-line prefer-arrow/prefer-arrow-functions
            function onSuccess(heading: DeviceOrientationCompassHeading) {
                subscriber.next(heading);
            }

            // eslint-disable-next-line prefer-arrow/prefer-arrow-functions
            function onError(_compassError: any) {
                // console.info('Compass error: ' + compassError.code);
                // subscriber.error(compassError);
                // TODO: log the error?
            }

            const compassOptions: DeviceOrientationCompassOptions = {
                frequency
            };

            const watchID = (navigator as any).compass.watchHeading(onSuccess, onError, compassOptions);

            // Provide a way of canceling and disposing the interval resource
            return () => {
                (navigator as any).compass.clearWatch(watchID);
            };
        });

        return observable;

    }
```
