### ISSUE TITLE
@ionic-native/barcode-scanner: Add property "saveHistory" into interface BarcodeScannerOptions

### ISSUE THREAD

**Issue by SoraNoIseki** [danielsogl/awesome-cordova-plugins#3661]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request

**Related code:**

**@ionic-native/barcode-scanner/index.d.ts**

```
export interface BarcodeScannerOptions {
    ...
    /**
     * Android, save scan history
     */
    saveHistory?: boolean;
}
```

**Other information:**
Hi dear ionic developers, I have a feature request about the plugin @ionic-native/barcode-scanner: Is it possible to add a property "saveHistory" into interface BarcodeScannerOptions? 

For my project i needed to disable the "saveHistory" feature while scanning a QR-code, cause some private data such as password would be saved in Android devices. So i've tried to add this property to the interface and it works. 

It would be nice if this could be official supported, thanks :D

**Comment by Fokarr** [comment]
I had the same problem!
