### ISSUE TITLE
Support rxjs 7

### ISSUE THREAD

**Issue by WIStudent** [danielsogl/awesome-cordova-plugins#3691]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently ionic-native packages cannot be installed together with rxjs@7 using npm@7 because they do not list rxjs@7 as a valid version in their peerDependencies.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: rxjs@7.1.0
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"^7.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^5.5.0 || ^6.5.0" from @ionic-native/barcode-scanner@5.33.0
npm ERR! node_modules/@ionic-native/barcode-scanner
npm ERR!   @ionic-native/barcode-scanner@"^5.33.0" from the root project
```

**Expected behavior:**

It should be possible to use ionic-native packages together with rxjs@7

**Steps to reproduce:**

Try installing an ionic-native package (for example @ionic-native/barcode-scanner) together with rxjs@7 using npm@7

**Comment by WIStudent** [comment]
We are using capacitor +  vue + phonegap-plugin-barcodescanner + @ionic-native/barcode-scanner in our app. 

Interestingly `@ionic-native/barcode-scanner` imports from `@angular/core`, but does not decalre `@angular/core` as a (peer)dependency in its package.json
https://github.com/ionic-team/ionic-native/blob/f19ddc7cdedbe757c17695e48ca3e691b8ce597b/src/%40ionic-native/plugins/barcode-scanner/index.ts#L1

```
{
  "description": "Ionic Native - Native plugins for ionic apps",
  "main": "bundle.js",
  "module": "index.js",
  "typings": "index.d.ts",
  "author": "ionic",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/ionic-team/ionic-native.git"
  },
  "name": "@ionic-native/barcode-scanner",
  "dependencies": {
    "@types/cordova": "latest"
  },
  "peerDependencies": {
    "rxjs": "^5.5.0 || ^6.5.0",
    "@ionic-native/core": "^5.1.0"
  },
  "version": "5.33.1"
}

```
At the same time `@ionic-native/barcode-scanner` is declaring `rxjs` as a peer dependency although it does not use it(?)


`@ionic-native/core` also does not decare angular as a (peer)dependency.
```
{
  "description": "Ionic Native - Native plugins for ionic apps",
  "main": "bundle.js",
  "module": "index.js",
  "typings": "index.d.ts",
  "author": "ionic",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/ionic-team/ionic-native.git"
  },
  "name": "@ionic-native/core",
  "dependencies": {
    "@types/cordova": "latest"
  },
  "peerDependencies": {
    "rxjs": "^5.5.0 || ^6.5.0"
  },
  "version": "5.33.1"
}
```

That's how we get this error only with ionic-native when we are trying to update to rxjs 7. We do not have angular in our dependency tree.


Then again, in our particular case it might be time to ditch `phonegap-plugin-barcodescanner` and replace it with a [capacitor plugin](https://github.com/capacitor-community/barcode-scanner) or a pure [web implementation](https://github.com/zxing-js/library) now that iOS 14.3 supports `getUserMedia()` inside the webview. Currently `@ionic-native/barcode-scanner` is the only ionic-native dependency that we are using.

**Comment by almothafar** [comment]
I think Angular 12 (and 11.2.13) should be supporting rxjs 7

mentioned here https://github.com/angular/angular/blob/master/CHANGELOG.md#1200-2021-05-12
and here https://github.com/angular/angular/blob/master/CHANGELOG.md#1200-2021-05-12

**Comment by jdforsythe** [comment]
We have no issue that I can tell running Angular 12.2.2 with rxjs 7 except the peer dependency warnings from `@ionic-native/core`, `@ionic-native/splash-screen`, and `@ionic-native/status-bar`
