### ISSUE TITLE
Apple pay for ionic capacitor - question

### ISSUE THREAD

**Issue by alferus** [danielsogl/awesome-cordova-plugins#3695]
Hello everybody! Does anyone know or can advise a working plugin Apple Pay for ionic capacitor 2 vue.js?

**Comment by Sitronik** [comment]
> Hello everybody! Does anyone know or can advise a working plugin Apple Pay for ionic capacitor 2 vue.js?

Hello, you can try my plugin: 
https://github.com/Sitronik/capacitor-3-apple-pay
But you need upgrade to capacitor 3
