### ISSUE TITLE
Support new functions onesignal-cordova-plugin 3.0.0

### ISSUE THREAD

**Issue by maxfloden** [danielsogl/awesome-cordova-plugins#3722]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Does not recognise new functions in onesignal-cordova-plugin / OneSignal-Cordova-SDK 3.0.0, for example the new init OneSignal.setAppId()

**Expected behavior:**
Should be updated to support new v3 functions (and reflect removed functions from v2)

**Steps to reproduce:**
N/A

**Related code:**
N/A

**Other information:**
OneSignal Cordova 3.0.0 was just released (11 days ago) and is no longer in beta.
https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/3.0.0
https://documentation.onesignal.com/docs/cordova-30-api-reference

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 6.17.0 (/Users/maxfloden/.nvm/versions/node/v14.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.13
   @angular-devkit/build-angular : 12.2.1
   @angular-devkit/schematics    : 12.1.2
   @angular/cli                  : 12.2.1
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 10.0.1, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 16 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : not installed globally

System:

   Android SDK Tools : 26.1.1 (/Users/maxfloden/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v14.16.0 (/Users/maxfloden/.nvm/versions/node/v14.16.0/bin/node)
   npm               : 6.14.13
   OS                : macOS Big Sur
   Xcode             : Xcode 12.5 Build version 12E262
```

**Comment by davequested** [comment]
+1 Would be great to get this working with the latest OneSignal plugin.

**Comment by rbalet** [comment]
Could this issue relate to the latest smartphone `Samsung S21` & `Huawei P30 Pro`  not receiving the oneSignal notification anymore?

**Comment by alexp25** [comment]
It doesn't work with the latest onesignal plugin. From 3.0.0, there are breaking changes and the methods defined in this wrapper no longer work.
`Native: tried calling OneSignal.startInit, but the OneSignal plugin is not installed.`
https://stackoverflow.com/questions/67454035/ionic-cordova-app-says-plugin-not-installed-even-after-installed

**Comment by LeandroFChaves** [comment]
Hi,

Was there any update?

Thanks

**Comment by arihantdaga** [comment]
Can we reopen this issue, as this is still an issue, i am getting the same error. `"Native: tried calling OneSignal.startInit, but the OneSignal plugin is not installed`
