### ISSUE TITLE
issue after merge the pull request #3612

### ISSUE THREAD

**Issue by mostafa-mansour1** [danielsogl/awesome-cordova-plugins#3770]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

after merging the pull request here 
https://github.com/ionic-team/ionic-native/pull/3612
it's merged only here, but the changes do not appear in https://ionicframework.com/docs/native/preview-any-file and do not appear here also https://www.npmjs.com/package/@ionic-native/preview-any-file
Does it need any change from my side?

**Comment by Siedlerchr** [comment]
I guess you have to wait until they release a new version of ionic native

**Comment by mrogunlana** [comment]
the `@ionic-native/preview-any-file` npm version has still not been updated in 2022

re: @mostafa-mansour1

**Comment by mostafa-mansour1** [comment]
Run it directly as a cordova code without ionic wrapper


Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466


On 12 Apr 2022, at 12:08 PM, Diran Ogunlana ***@***.***> wrote:

﻿

also @mostafa-mansour1<https://github.com/mostafa-mansour1> I'm not sure if copying the wrapper manually to the node_modules folder (re: mostafa-mansour1/previewAnyFile#14 (comment)<https://github.com/mostafa-mansour1/previewAnyFile/issues/14#issuecomment-771783669>) will apply to a production scenario. do you suggest any longer term alternative?

**Comment by mrogunlana** [comment]
@mostafa-mansour1 I'm running: 

```
(<any>window).PreviewAnyFile.previewBase64(document.content, { mimeType: document.contentType, name: filename.replace(/\s+/g, '') })
            .then((res) => { console.log(`Preview resource: ${res}`) })
            .catch((error) => { console.log(`Error previewing ${filename}.`, error) });
```
and am still getting the following error: 

```
ERROR Error: Uncaught (in promise): Error: The old format of this exec call has been removed (deprecated since 2.1). Change to: cordova.exec(null, null, 'Service', 'action', [ arg1, arg2 ]);
Error: The old format of this exec call has been removed (deprecated since 2.1). Change to: cordova.exec(null, null, 'Service', 'action', [ arg1, arg2 ]);
```

am I missing something here?

**Comment by mrogunlana** [comment]
@mostafa-mansour1 thank you for your help, that worked for me. now if we could just get `@ionic-native/preview-any-file` uploaded with your latest changes, that would be great. if there's anything I could do to help, let me know
