### ISSUE TITLE
Missing plugins since moving to new repository

### ISSUE THREAD

**Issue by DavidStrausz** [danielsogl/awesome-cordova-plugins#3787]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
It seems since moving to the new repo a lot of plugins are missing, or were removed without notice.

**Expected behavior:**
The same plugins which were available via the @ionic-native org should be available in the @awesome-cordova-plugins org.

**Steps to reproduce:**
Try to install one of the following plugins:

```
npm i @awesome-cordova-plugins/android-fingerprint-auth
npm i @awesome-cordova-plugins/qr-scanner
npm i @awesome-cordova-plugins/siri-shortcuts
```

Every one of them will produce a 404 error from npm:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@awesome-cordova-plugins%2fandroid-fingerprint-auth - Not found
npm ERR! 404 
npm ERR! 404  '@awesome-cordova-plugins/android-fingerprint-auth@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.8.1
   @angular-devkit/build-angular : 12.2.7
   @angular-devkit/schematics    : 12.2.7
   @angular/cli                  : 12.2.7
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 23 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : not installed globally

System:

   Android SDK Tools : 26.1.1 (/Users/---/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.2
   NodeJS            : v14.17.0 (/usr/local/bin/node)
   npm               : 7.24.1
   OS                : macOS Big Sur
   Xcode             : Xcode 12.5.1 Build version 12E507
```

**Comment by danielsogl** [comment]
I explained the reasons in this issue: https://github.com/danielsogl/awesome-cordova-plugins/issues/3778

**Comment by DavidStrausz** [comment]
@danielsogl Thanks for your answer. Whats the recommendation for cordova users? A very big part of the community uses ionic-native with cordova and not with capacitor. Also, I don't really understand the benefit of just removing the wrappers for the sake of removing them, there is no additional maintenance effort in keeping them in the build, plus this way you are not breaking the apps of all the folks using these plugins :)

**Comment by QuentinFarizon** [comment]
@danielsogl qr-scanner plugin has been deemed unmaintained, but it worked very well (thus no maintenance needed ? ;) ) and has no replacement ... I'm not really understanding the removal

**Comment by helpmetheroadassistanceapp** [comment]
Hello, any news? This plugins is really good.
