### ISSUE TITLE
Any plans to also migrate @ionic-native/google-maps?

### ISSUE THREAD

**Issue by mcastets** [danielsogl/awesome-cordova-plugins#3820]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

Why the [@ionic-native/google-maps](https://github.com/ionic-team/ionic-native-google-maps) has not been migrated yet? 

This prevents from migrating to `@awesome-cordova-plugins/core` because the google maps plugin still has a dependency to `@ionic-native/core`.

```
Error: node_modules/@ionic-native/google-maps/ngx/index.d.ts:1:35 - error TS2307: Cannot find module '@ionic-native/core' or its corresponding type declarations.

1 import { IonicNativePlugin } from '@ionic-native/core';
```

**Expected behavior:**

Google Maps should be under this repository and the dependency to `IonicNativePlugin` should be replaced by `AwesomeCordovaNativePlugin`

**Comment by fredroo** [comment]
+1

**Comment by fredroo** [comment]
Why not import google-maps from ionic native project official
