### ISSUE TITLE
inAppBrowser shouldAutorotateToInterfaceOrientation iOS fails to build error.

### ISSUE THREAD

**Issue by parksmart-dev** [danielsogl/awesome-cordova-plugins#3855]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
On build.

CDVInAppBrowserNavigationController.m
No known instance method for selector 'shouldAutorotateToInterfaceOrientation:'

**Steps to reproduce:**
"@awesome-cordova-plugins/in-app-browser": "^5.37.0",
"cordova-ios": "6.2.0",
XCode v12.1

**Comment by danielsogl** [comment]
You should then open a issue at the plugins source because this repo just wrapps it: https://github.com/apache/cordova-plugin-inappbrowser
