### ISSUE TITLE
NOT WORKING ON ANDROID FOR GOOGLE LOGIN

### ISSUE THREAD

**Issue by wang1314chris** [danielsogl/awesome-cordova-plugins#3896]
I Am using ccapacitor to run the project.

install:  "@awesome-cordova-plugins/google-plus" & "cordova-plugin-googleplus" by using npm install
However when I call the

     this.googlePlus.login({
      'scopes':  'profile email', 
      'webClientId': 'xxxx.apps.googleusercontent.com'
      'offline':  false    
    }).then(res => {
      console.log('Google Response: ',res);
    }).catch(err => {
      console.log('Google Error: ',err);
    });    

I got nothing, not even an error message, the package does log the corect result in android, but doesn't return out to my frontend.

What is wrong?

Thanks

Ps.: I have already checked my client ID and reversed client ID.

**Comment by fredroo** [comment]
https://stackoverflow.com/questions/50248555/ionic-native-googleplus-login-fails-without-any-error
