### ISSUE TITLE
Imcompatibility with rxjs v7 (need support for Angular 13)

### ISSUE THREAD

**Issue by sinedied** [danielsogl/awesome-cordova-plugins#3897]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm trying to use rxjs v7 in my project (needed by some dependencies after Angular v13 upgrade), and running `npm install` in my project fails because of `peer rxjs@"^5.5.0 || ^6.5.0" from @ionic-native/*`.

**Expected behavior:**
I can run `npm install` without having to use the `--force` option.

**Steps to reproduce:**
1. Create a new Angular project with rxjs v7, and add any @ionic-native module.
2. Try to run `npm install`

**Other information:**
I cannot downgrade to rxjs v6, as some other Angular dependencies (other that core modules) need rxjs v7 to work.

**Comment by Nierifeng** [comment]
+1

**Comment by fredroo** [comment]
+1

**Comment by sinedied** [comment]
Replacing all `@ionic-native` occurences with `@awesome-cordova-plugins` in package.json seems to solve the issue.
I missed the migration native, a deprecation warning on `@ionic-native` packages might be useful here.

**Comment by fredroo** [comment]
@sinedied ionic native google maps?

**Comment by danielsogl** [comment]
@fredroo I'm not maintaining this plugin. You have to reach out to the maintainer of the maps plugin repo

**Comment by fredroo** [comment]
https://github.com/danielsogl/awesome-cordova-plugins/issues/3820 @danielsogl take a look
