### ISSUE TITLE
Error Ionic 6

### ISSUE THREAD

**Issue by Shemo01** [danielsogl/awesome-cordova-plugins#3909]
>ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module
       '@capacitor/ios/package'

       Require stack:
       -
       C:\Users\Administrador\AppData\Roaming\nvm\v16.13.1\node_modules\@ionic\cli\lib\project\index.js
       -
       C:\Users\Administrador\AppData\Roaming\nvm\v16.13.1\node_modules\@ionic\cli\lib\index.js 
       - C:\Users\Administrador\AppData\Roaming\nvm\v16.13.1\node_modules\@ionic\cli\index.js   
       - C:\Users\Administrador\AppData\Roaming\nvm\v16.13.1\node_modules\@ionic\cli\bin\ionic  
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module
       '@capacitor/android/package'

       Require stack:
       -
       C:\Users\Administrador\AppData\Roaming\nvm\v16.13.1\node_modules\@ionic\cli\lib\project\index.js
       -
       C:\Users\Administrador\AppData\Roaming\nvm\v16.13.1\node_modules\@ionic\cli\lib\index.js 
       - C:\Users\Administrador\AppData\Roaming\nvm\v16.13.1\node_modules\@ionic\cli\index.js   
       - C:\Users\Administrador\AppData\Roaming\nvm\v16.13.1\node_modules\@ionic\cli\bin\ionic  

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\Administrador\AppData\Roaming\nvm\v16.13.1\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.0
   OS     : Windows 10

Error npm install native plugins the Ionic 6

npm install @awesome-cordova-plugins/camera
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: GoFrimac@0.0.1
npm ERR! Found: rxjs@6.6.7
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~6.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^5.5.0 || ^7.3.0" from @awesome-cordova-plugins/core@5.37.1       

----->npm install @awesome-cordova-plugins/camera
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: GoFrimac@0.0.1
npm ERR! Found: rxjs@6.6.7
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~6.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^5.5.0 || ^7.3.0" from @awesome-cordova-plugins/core@5.37.1

help ????

**Comment by dragermrb** [comment]
Hi!

Commit https://github.com/danielsogl/awesome-cordova-plugins/commit/cd477bce7c40c22eababb87f2f14c79ecb5b78ec allows **rxjs 7.x**, but disallows **rxjs 6.x**. I don't know why.

Maybe `^5.5.0 || ^6.5.0 || ^7.3.0` is a better option?

**Comment by h4de5** [comment]
Please update peerDependency as suggested to support rxjs ^6.5.0 again.

working with apollo-angular here, which has hard limit on rxjs^6
