### ISSUE TITLE
@awesome-cordova-plugins/app-minimize is missing.

### ISSUE THREAD

**Issue by nothingkid** [danielsogl/awesome-cordova-plugins#3926]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

**@awesome-cordova-plugins/app-minimize** is missing.
According to https://ionicframework.com/docs/native/app-minimize **npm install @awesome-cordova-plugins/app-minimize** should install plugin, but instead I get this 
![Screenshot_436](https://user-images.githubusercontent.com/22461210/146566720-24644b54-fb87-4e1b-911b-ed7de27b60d4.png)

Am I missing something?

**Comment by danielsogl** [comment]
The Ionic team removed all outdated and unmaintained plugins from this repo. You should replace your cordova based plugins with capacitor plugins if possible.
