### ISSUE TITLE
Some capacitor plugins and typings for Ionic 6 are missing in https://registry.npmjs.org

### ISSUE THREAD

**Issue by AndrewBargan** [danielsogl/awesome-cordova-plugins#3931]
**I'm submitting a ...**  (check one with "x")
[x] bug report

These commands are taken from https://ionicframework.com/docs/native and cause "missing" error on installation

npm install @awesome-cordova-plugins/contacts
npm install @awesome-cordova-plugins/apple-pay
npm install cordova-approov-advanced-http
npm install @awesome-cordova-plugins/sim  

**Current behavior:**
404 Not Found - GET https://registry.npmjs.org/* - Not found

**Expected behavior:**
all packages installed properly

**Ionic info:**
Ionic 6

**Comment by danielsogl** [comment]
Hi, we (or better the Ionic team), removed all unmaintained plugins and plugins replaced by Capacitor plugins.You should migrate your application to capacitor and try to replace all cordova plugins with capacitor plugins,

**Comment by AndrewBargan** [comment]
Hey,

I don't see any capacitor plugins for sim and apple-pay here https://github.com/orgs/capacitor-community/repositories?q=&type=all. Where I can find substitution for these plugins?

Thanks.
- Andrew.
