### ISSUE TITLE
@awesome-cordova-plugins/crop is not in the npm registry

### ISSUE THREAD

**Issue by ghonche** [danielsogl/awesome-cordova-plugins#3934]
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The plugin `@awesome-cordova-plugins/crop` is mentioned in[ ionic docs](https://ionicframework.com/docs/native/crop) but can not be found in npm registry.

**Steps to reproduce:**
When running this command:
>  npm install @awesome-cordova-plugins/crop 

I get the following error:

> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@awesome-cordova-plugins%2Fcrop - Not found
> npm ERR! 404 
> npm ERR! 404  '@awesome-cordova-plugins/crop@latest' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Ionic info:** 
```Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI   : 3.3.3
   @capacitor/core : 3.3.3

Utility:

   cordova-res : not installed
   native-run  : 1.5.0

System:

   NodeJS : v14.18.2 (/home/ghonche/.nvm/versions/node/v14.18.2/bin/node)
   npm    : 6.14.15
   OS     : Linux 5.11

**Comment by ravatsinh** [comment]
I am also getting same error 
`npm install @awesome-cordova-plugins/crop`

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@awesome-cordova-plugins%2fcrop - Not found
npm ERR! 404
npm ERR! 404  '@awesome-cordova-plugins/crop@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

Ionic Info
```
Ionic:
   Ionic CLI                     : 6.18.1
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:
   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3

Utility:
   cordova-res : not installed globally
   native-run  : 1.5.0

System:
   NodeJS : v16.13.1 
   npm    : 8.3.0
   OS     : Windows 10
```

**Comment by kensodemann** [comment]
At the time of the move, many outdated and unmaintained plugins had their wrappers removed. This was one of those. The Ionic docs site has not been fully updated yet to reflect this.

If you still want to use the underlying plugin, I suggest only installing the plugin and not the (non-existent) `@awesome-cordova-plugins` wrapper. You can then abstract all of the usage of the plugin into your own service that meets your particular needs.

**Comment by ghonche** [comment]
> At the time of the move, many outdated and unmaintained plugins had their wrappers removed. This was one of those. The Ionic docs site has not been fully updated yet to reflect this.
> 
> If you still want to use the underlying plugin, I suggest only installing the plugin and not the (non-existent) `@awesome-cordova-plugins` wrapper. You can then abstract all of the usage of the plugin into your own service that meets your particular needs.


Thanks for the explanation. So I guess the ionic docs better be updated to prevent further confusion.
