### ISSUE TITLE
market plugin missing

### ISSUE THREAD

**Issue by Slavrix** [danielsogl/awesome-cordova-plugins#3935]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
this plugin is missing
https://ionicframework.com/docs/native/market

**Expected behavior:**
this plugin to not be missing
https://ionicframework.com/docs/native/market

**Steps to reproduce:**
npm install @awesome-cordova-plugins/market

plugin not found

Any reason its not included? I couldn't see any replacements for it.
My use case is to open the marketplace for android or ios and allow the user to update their app from there if they have an older version.

**Comment by danielsogl** [comment]
The Ionic team removed all outdated and unmaintained plugins from this repo.
