### ISSUE TITLE
Plugins missing "emm-app-config" "market"

### ISSUE THREAD

**Issue by alegueut** [danielsogl/awesome-cordova-plugins#3939]
**I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
Plugins are missing
https://ionicframework.com/docs/native/market
https://ionicframework.com/docs/native/emm-app-config

**Expected behavior:**
A transparent migration to awesome-cordova-plugins.

**Steps to reproduce:**
Try to install these from @awesome-cordova-plugins

plugin not found

**Comment by danielsogl** [comment]
The Ionic team removed all outdated and unmaintained plugins from this repo.
