### ISSUE TITLE
Market Plugin is Missing, Please Check.

### ISSUE THREAD

**Issue by OHELLEL** [danielsogl/awesome-cordova-plugins#3942]
**I'm submitting a ...**
[ x ] bug report
[   ] feature request
[   ] support request

**Current behavior:**
Log: 
    npm ERR! 404 Not Found - GET https://registry.npmjs.org/@awesome-cordova-plugins%2fmarket - Not found

**Expected behavior:**
+ @awesome-cordova-plugins/market@5.36.0

**Comment by danielsogl** [comment]
The Ionic team removed all outdated and unmaintained plugins from this repo.

**Comment by rodrigograca31** [comment]
@danielsogl why do they tell us to install it from `@awesome-cordova-plugins` then?

https://ionicframework.com/docs/native/market

**Comment by rodrigograca31** [comment]
Do we use `@ionic-native/market` then? 
if so, will we need `@ionic-native/core` in addition to `@awesome-cordova-plugins/core` ? or only the latter? 🤔
