### ISSUE TITLE
Ionic v5 , V6 not working with angular 13. ( Rxjs )

### ISSUE THREAD

**Issue by phyr0s** [danielsogl/awesome-cordova-plugins#3946]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Native plugins wrapper is not valid with ionic 5.X, 6.X and angular 13

**Expected behavior:**
Expected to compile with angular 13

**Steps to reproduce:**
Just create new project upgrade to angular 13 and lastest version of ionic V5

**Related code:**

```
Found: rxjs@7.4.0 (angular 13)

Error --> 
 peer rxjs@"^5.5.0 || ^6.5.0" from @ionic-native/core@5.36.0
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
  Ionic CLI                     : 6.18.1
   Android SDK Tools : 26.1.1 
   NodeJS            : v16.13.1
   npm               : 8.1.2
   OS                : macOS Monterey
   Xcode             : Xcode 13.1 Build version 13A1030d

 Ionic Framework               : @ionic/angular 5.9.3
   @angular-devkit/build-angular : 13.1.1
   @angular-devkit/schematics    : 13.1.1
   @angular/cli                  : 13.1.1
   @ionic/angular-toolkit        : 5.0.3

```

**Comment by danielsogl** [comment]
You have to upgrade your packages to the new repo: https://ionicframework.com/blog/a-new-chapter-for-ionic-native/
