### ISSUE TITLE
Error in printer plugin how to solve ?

### ISSUE THREAD

**Issue by anees-synavos** [danielsogl/awesome-cordova-plugins#3959]
ERROR in /.../node_modules/@awesome-cordova-plugins/printer/ngx/index.js
Module not found: Error: Can't resolve '@awesome-cordova-plugins/core' in '/.../node_modules/@awesome-cordova-plugins/printer/ngx'

**Comment by filippodicostanzo** [comment]
just install @awesome-cordova-plugins/core package
