### ISSUE TITLE
Where is DatePicker wrapper?

### ISSUE THREAD

**Issue by rvcroffi** [danielsogl/awesome-cordova-plugins#3962]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I followed the [datepicker plugin doc](https://ionicframework.com/docs/v5/native/date-picker) and got this error:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@awesome-cordova-plugins%2fdate-picker - Not found
npm ERR! 404
npm ERR! 404  '@awesome-cordova-plugins/date-picker@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Expected behavior:**
@awesome-cordova-plugins/date-picker successfully installed.

**Steps to reproduce:**
`npm install @awesome-cordova-plugins/date-picker`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 6.18.1
   Ionic Framework               : @ionic/angular 5.9.2
   @angular-devkit/build-angular : 12.2.14
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 12.2.14
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.4
   @capacitor/core    : 3.3.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.18.1 (C:\Program Files\nodejs\node.exe)
   npm    : 7.16.0
   OS     : Windows 10
```

**Comment by bhargavas12** [comment]
@rvcroffi  any idea on how to update ionic-native/date-picker module to awesome-cordova ?
