### ISSUE TITLE
firebase-x, increment should have 2 parameters

### ISSUE THREAD

**Issue by MauriceSchoenmakers** [danielsogl/awesome-cordova-plugins#3970]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
FirebaseX.incrementCounter has two parameters, now we get a type error when we pass 2 parameters

**Expected behavior:**
correct typescript type

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by danielsogl** [comment]
Feel free to adjust the interface and create a pull request. I will review your changes: https://github.com/danielsogl/awesome-cordova-plugins/blob/master/src/%40awesome-cordova-plugins/plugins/firebase-x/index.ts
