### ISSUE TITLE
@awesome-cordova-plugins/core in file common.d.ts cannot find name 'unknown'.

### ISSUE THREAD

**Issue by carmenpy** [danielsogl/awesome-cordova-plugins#3975]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When I run my ionic project on android or ios platform I get the following error from @awesome-cordova-plugins/core dependency

typescript: node_modules/@awesome-cordova-plugins/core/decorators/common.d.ts, line: 9 
Cannot find name 'unknown'. 

L8:  export declare function getPromise<T>(callback: (resolve: Function, reject?: Function) => any): Promise<T>;
L9:  ction wrapPromise(pluginObj: any, methodName: string, args: any[], opts?: CordovaOptions): Promise<unknown>;

**Ionic info:** (run ionic info from a terminal/cmd prompt and paste output below):
Ionic:
   Ionic CLI          : 5.4.16 
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.0

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : no whitelisted plugins (21 plugins total)

**Comment by RafaelPuerta** [comment]
u need change "unknown" to "any" with that it will work but it is not the best solution since you have to do it manually

**Comment by carmenpy** [comment]
Thanks, that's how it's solved.
