### ISSUE TITLE
Application crashes on Android 11 onward on execution of emailComposer.open()

### ISSUE THREAD

**Issue by pmahajan31** [danielsogl/awesome-cordova-plugins#4005]
An android application gets crashed on Android11 using a capacitor, when emailComposer.open() is called.
Even though we have asked for GET_ACCOUNTS permission and made allowed, it still returns false for emailComposer.hasPermission().

Error is:
`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0`
for list of target from `getDrafts()` method.

It works perfectly fine with Android 10 and lower versions.
Please help here!

**Comment by nsonanh** [comment]
I got the same issue, this is the log:

`E/AndroidRuntime: FATAL EXCEPTION: pool-5-thread-2
    Process: com.centivalife, PID: 27650
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at java.util.ArrayList.remove(ArrayList.java:506)
        at nl.xservices.plugins.SocialSharing$1.run(SocialSharing.java:199)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)`

**Comment by nsonanh** [comment]
FYI: I fixed this issue by installing the email-composer plugin: https://ionicframework.com/docs/native/email-composer. I didn't even have to update the code to use it, the app stops crashing and I can send email normally now.
