### ISSUE TITLE
No disableReaderMode() function for NFC plugin

### ISSUE THREAD

**Issue by cyrilfr** [danielsogl/awesome-cordova-plugins#4107]
According to the [phonegap-nfc GitHub page](https://github.com/chariotsolutions/phonegap-nfc#nfcdisablereadermode), you should be able to disable the read mode once the read process is finished.

It's currently not the case so even after a call to `unsubscribe()` on the `readerMode()` function, the phone still continue to vibrate, indicating that a RFID tag has been read.

**Comment by phpfs** [comment]
I run into the same problem, though it should be quite easy to add this as a function!

**Comment by VasanthCBH** [comment]
@phpfs - I am facing the same issue in android and I have tried to unsubscribe() -> but it is opening up an model with read data as default. Pls comment on the same

**Comment by phpfs** [comment]
> @phpfs - I am facing the same issue in android and I have tried to unsubscribe() -> but it is opening up a model with read data as default. Pls comment on the same

Hi @VasanthCBH - this is normal behavior on Android and not something you can tamper with. As long as you are subscribed, you'll get all events triggered by the observable - if you're not the OS will handle them. Our solution was to keep the subscription active just a little longer than the actual reading process requires and thereby catch accidental "double reads" the user may cause. In case you want to prevent the OS from handling any events while your app is in the foreground, simply keep the subscription active _all the time_ and dispose events received outside of the actual scanning process :)
