### ISSUE TITLE
background-mode doesn't compile in Capacitor 3 Angular application

### ISSUE THREAD

**Issue by MadEddieFFS** [danielsogl/awesome-cordova-plugins#4113]
I am trying to use the background mode plugin with Capacitor 3 and Angular.

app.component.ts
````
import { BackgroundMode } from '@awesome-cordova-plugins/background-mode/ngx';
....
constructor(private backgroundMode:BackgroundMode  ) { }
....
 ngOnInit(): void {
    this.backgroundMode.enable();
}
````

But "ng build" and "npx cap sync" both work however the Gradle/Android Studio building fails:
Originally it failed with aot errors so I changed to building with --aot=false --build-optimiser=false to correct this - but now I get the below.
````
Line 1 - Msg: Native: tried calling BackgroundMode.enable, but the BackgroundMode plugin is not installed.
Line 1 - Msg: Install the BackgroundMode plugin: 'ionic cordova plugin add cordova-plugin-background-mode'
Line 1 - Msg: Native: tried calling BackgroundMode.isEnabled, but the BackgroundMode plugin is not installed.
Line 1 - Msg: Install the BackgroundMode plugin: 'ionic cordova plugin add cordova-plugin-background-mode'
````

Any help would be appreciated as I understand the plugins etc aren't installed as I am using Capacitor + Angular, not Cordova and/or Ionic

**Comment by iAmServer** [comment]
were you able to resolve this?

**Comment by MadEddieFFS** [comment]
Sorry - I worked around the problem by creating my own plugin

**Comment by iAmServer** [comment]
Okay thanks, I was able to fix it after several tries.

Downgrades the plugin and it worked
