### ISSUE TITLE
cordova-approov-advanced-http doesn't exist on npm

### ISSUE THREAD

**Issue by jcesarmobile** [danielsogl/awesome-cordova-plugins#4149]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
npm install fails for cordova-approov-advanced-http
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
npm install cordova-approov-advanced-http
```

**Other information:**

The plugins was added here, but it doesn't exist on npm
https://github.com/danielsogl/awesome-cordova-plugins/pull/3682

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jcesarmobile** [comment]
The issue is still relevant

**Comment by jcesarmobile** [comment]
The issue is still relevant

**Comment by danielsogl** [comment]
Hi, the Ionic team removed all cordova plugins that could be replaced with capacitor plugins. This is why some plugins are missing.

**Comment by jcesarmobile** [comment]
The issue is about the install instructions indicating to use cordova-approov-advanced-http package, but that package doesn’t exist
