### ISSUE TITLE
Update documentation @awesome-cordova-plugins/background-geolocation

### ISSUE THREAD

**Issue by josuelmm** [danielsogl/awesome-cordova-plugins#4153]
Currently the documentation of
@awesome-cordova-plugins/background-geolocation
point to download
npm install @mauron85/cordova-plugin-background-geolocation

This plugin has not been updated for years, the most stable plugin that works perfectly is
https://www.npmjs.com/package/cordova-background-geolocation-plugin

To download it use:
npm i cordova-background-geolocation-plugin

Tested by me, 100% the plugin and it is 100% correct.

**Comment by cristiancarmona** [comment]
Thank you @josuelmm  , i have a question, what is the method to import this plugin in my angular page (components ) and module.  'import { BackgroundGeolocation } from '@xxxx' ?

**Comment by josuelmm** [comment]
You import as it appears in the documentation, this in the app.module

import { BackgroundGeolocation} from '@awesome-cordova-plugins/background-geolocation/ngx';

Y
import { BackgroundGeolocation, BackgroundGeolocationAccuracy, BackgroundGeolocationConfig, BackgroundGeolocationEvents, BackgroundGeolocationResponse } from '@awesome-cordova-plugins/background-geolocation/ngx';

On the page where you will use it
