### ISSUE TITLE
Missing plugins from @ionic-native

### ISSUE THREAD

**Issue by olivierschmid** [danielsogl/awesome-cordova-plugins#4155]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I am migrating the wrapper packages from @ionic-native to @awesome-cordova-plugins. I could migrate all plugins expect of these:
- @ionic-native/crop
- @ionic-native/file-chooser
- @ionic-native/file-picker

Any plans to provide them?
Thanks!

Output from ionic info
```
Ionic:

   Ionic CLI                     : 6.18.1 (/Users/olivierschmid/.nvm/versions/node/v14.17.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.8.5
   @angular-devkit/build-angular : 12.2.14
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 12.2.14
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 26 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.5.0)   : 1.4.0

System:

   Android SDK Tools : 26.1.1 (/Users/olivierschmid/Library/Android/sdk)
   ios-deploy        : 1.11.3
   ios-sim           : 8.0.2
   NodeJS            : v14.17.0 (/Users/olivierschmid/.nvm/versions/node/v14.17.0/bin/node)
   npm               : 7.16.0
   OS                : macOS Monterey
   Xcode             : Xcode 13.2.1 Build version 13C100

**Comment by jneterer** [comment]
I'm getting the same error today.

**Comment by ryaa** [comment]
I have also failed to migrate @ionic-native/file-chooser to awesome-cordova-plugins as well as image-resizer (https://github.com/danielsogl/awesome-cordova-plugins/issues/4203)

**Comment by ryaa** [comment]
Any plans to cover the above plugins?

**Comment by Chachuke** [comment]
I see the status inactive was removed, but is there any news on this ?
I currently can't get the ios file picker working in an ionic 6 project with awesome-cordova-plugin.

There is errors with the npm command due to the uppercase letter : `$ ionic cordova plugin add cordova-plugin-documentpicker.DocumentPicker `
And if i install directly from the github page, it is not working with ionic

**Comment by ryaa** [comment]
I have created the PR to enable file-chooser - see https://github.com/danielsogl/awesome-cordova-plugins/pull/4396
