### ISSUE TITLE
@awesome-cordova-plugins/barcode-scanner uses deprecated phonegap-plugin-barcodescanner. Is there a plan to replace?

### ISSUE THREAD

**Issue by jimbarrett33** [danielsogl/awesome-cordova-plugins#4166]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
the `@awesome-cordova-plugins/barcode-scanner` uses deprecated `phonegap-plugin-barcodescanner`. Is there a plan to replace the deprecated phone gap plugin?

**Expected behavior:**
Seems to still be working but seems this is an eventual death march.

**Other information:**
https://www.npmjs.com/package/phonegap-plugin-barcodescanner
https://github.com/phonegap/phonegap-plugin-barcodescanner

**Comment by xulihang** [comment]
There is the [cordova-plugin-dynamsoft-barcode-reader](https://www.npmjs.com/package/cordova-plugin-dynamsoft-barcode-reader).

It uses the native camera preview and allows putting web elements on it.

You can check out this article: [Writing a Wrapper to use Cordova Plugins in an Ionic App](https://www.dynamsoft.com/codepool/cordova-plugin-ionic-wrapper.html)

**Comment by LeandroFChaves** [comment]
Up

**Comment by Constaline** [comment]
How about using [okhiroyuki/cordova-plugin-barcodescanner](https://github.com/okhiroyuki/cordova-plugin-barcodescanner) to replace ?
