### ISSUE TITLE
Missing @ionic-native/market

### ISSUE THREAD

**Issue by kesavadasu** [danielsogl/awesome-cordova-plugins#4175]
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Missing @ionic-native/market

**Expected behavior:**
Request you to include it under awesome-cordova-plugins

**Steps to reproduce:**
Unable to find the plugin in Ionic-5 native documentation pag

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Ionic:

   Ionic CLI                     : 6.17.0 (C:\Users\User\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.9.1
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 10.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 32 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.11.0
   native-run (update available: 1.4.0)   : 1.2.2

System:

 (C:\Users\User\AppData\Local\Android\sdk)
   NodeJS            : v14.17.5 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.9
   OS                : Windows 10```

**Comment by marshall86** [comment]
it would be great to have the migration of the plugin
