### ISSUE TITLE
I use ionic/VUE, how can I use this plugins?

### ISSUE THREAD

**Issue by luoliang222** [danielsogl/awesome-cordova-plugins#4193]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

[vue-cli-service] Module not found: Error: Can't resolve '@angular/core' in 'd:\work\test\yt\app2\node_modules\@awesome-cordova-plugins\wechat\ngx'
ERROR in ./node_modules/@awesome-cordova-plugins/wechat/ngx/index.js 2:0-43
[vue-cli-service] Module not found: Error: Can't resolve '@angular/core' in 'd:\work\test\yt\app2\node_modules\@awesome-cordova-plugins\wechat\ngx'
[vue-cli-service]  @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/login/login.vue?vue&type=script&lang=js 8:0-61 186:6-17
[vue-cli-service]  @ ./src/views/login/login.vue?vue&type=script&lang=js 1:0-203 1:0-203 1:204-396 1:204-396
[vue-cli-service]  @ ./src/views/login/login.vue 2:0-56 3:0-51 3:0-51 8:49-55
[vue-cli-service]  @ ./src/router/index.js 9:19-52
[vue-cli-service]  @ ./src/main.js 3:0-30 27:45-51 28:0-14 62:38-44
[vue-cli-service] webpack compiled with 1 error

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by sisou** [comment]
When using anything else than Angular, you need to import from the path without `/ngx` at the end. `ngx` stands for Angular.

In your case, import from `@awesome-cordova-plugins\wechat` instead.
