### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by amartino24** [danielsogl/awesome-cordova-plugins#4195]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
ng] Error: The target entry-point "@awesome-cordova-plugins/firebase-config" has missing dependencies:
[ng]  - @awesome-cordova-plugins/core

It suddenly starts to happen in my project. Any idea why? I was using the 5.40.0 version

**Comment by jeremyp1ttard** [comment]
Did you find a solution to this? I did a successful capacitor upgrade a few weeks ago, left it alone while work went on and now I've come back to it this is occurring
