### ISSUE TITLE
install cordova-plugin-sim

### ISSUE THREAD

**Issue by specchiasoft** [danielsogl/awesome-cordova-plugins#4200]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] support request 

**Current behavior:**
Unable to install on the Ionic Capacitor project cordova-plugin-sim project to get the phone number of the device. This plugin is listed in this git repository under src / index.ts: (import {Sim} from './plugins/sim'; but not in the / plugins folder nor in the Npm repository.
it appear also in https://github.com/danielsogl/awesome-cordova-plugins/pull/317 that means is included.

**Expected behavior:**
like tihis https://ionicframework.jp/docs/native/sim/
```
$ npm install cordova-plugin-sim 
$ npm install @awesome-cordova-plugins/sim 
$ ionic cap sync
```
Error:
@awesome-cordova-plugins/sim not exists in Npm repository

**Ionic info:** :

```
ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\s.pecchia\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.10
   @angular-devkit/build-angular : 12.2.14
   @angular-devkit/schematics    : 11.2.15
   @angular/cli                  : 12.2.14
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   Android SDK Tools : 26.1.1 (D:\Android\Sdk)
   NodeJS            : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.17
   OS                : Windows 10
```

**Comment by davidquon** [comment]
I've been looking for support for `cordova-plugin-sim` as well.  👍🏼
