### ISSUE TITLE
Missing @awesome-cordova-plugins/app-launcher

### ISSUE THREAD

**Issue by chrux** [danielsogl/awesome-cordova-plugins#4202]
**I'm submitting a ...** 
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Missing @awesome-cordova-plugins/app-launcher (PKA @ionic-native/app-launcher), I saw this reference https://ionicframework.jp/docs/native/app-launcher/ to this new project but I dont find it on npmjs or this repo/doc.

**Expected behavior:**
Request you to include it under awesome-cordova-plugins

**Comment by Yura13** [comment]
@danielsogl 
Any updates?
Do you plan to include supporting cordova-plugin-app-launcher in awesome-cordova-plugins?
