### ISSUE TITLE
Missing @ionic-native/screenshot

### ISSUE THREAD

**Issue by jack610336** [danielsogl/awesome-cordova-plugins#4223]
I'm submitting a ... (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

Current behavior:
Missing @ionic-native/screenshot

Expected behavior:
Please add  @ionic-native/screenshot to include it under awesome-cordova-plugins

Steps to reproduce:
Unable to install @awesome-cordova-plugins/screenshot

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@awesome-cordova-plugins%2fscreenshot - Not found
npm ERR! 404
npm ERR! 404  '@awesome-cordova-plugins/screenshot@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
Other information:
N/A

**Comment by thibaultv** [comment]
@jack610336 Hi.
Which plugin "@ionic-native/screenshot" is supposed to refer? You need to specify the exact Cordova plugin you want to use.
For information, you can easily create your own wrapper by reading the [following](https://github.com/danielsogl/awesome-cordova-plugins/blob/master/DEVELOPER.md) documentation.

**Comment by thibaultv** [comment]
Hi @mlynch ,
can you explain more about the "broken" status of this previous wrapper https://www.npmjs.com/package/@ionic-native/screenshot ?
Thanks
