### ISSUE TITLE
barcode-scanner

### ISSUE THREAD

**Issue by fabltd** [danielsogl/awesome-cordova-plugins#4239]
The barcode scanner appeares to be dependent on: phonegap-plugin-barcodescanner 

The project appears to be stale and as a result is producing errors. 

Is there an alterative to useing phonegap-plugin-barcodescanner ?

I had hoped this would be a replacement.

**Comment by sisou** [comment]
If you are building with Capacitor, there's an official capacitor-community plugin which I've been using with success: https://github.com/capacitor-community/barcode-scanner

**Comment by sisou** [comment]
See also #4166 for an alternative native plugin.
