### ISSUE TITLE
Type 'InAppBrowserOriginal' is not assignable to type 'Provider'

### ISSUE THREAD

**Issue by davvyy00** [danielsogl/awesome-cordova-plugins#4254]
import { InAppBrowser } from '@awesome-cordova-plugins/in-app-browser/ngx';

providers: [
        StatusBar,
        SplashScreen,
        Geolocation,
        Device,
        NativeStorage,
        File,
        FileOpener,
        FirebaseX,
        Deeplinks,
        InAppBrowser,
        Keyboard,
        Facebook,
        { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
        { provide: HTTP_INTERCEPTORS, useClass: RefreshTokenInterceptor, multi: true },
        { provide: HTTP_INTERCEPTORS, useClass: ErrorInterceptor, multi: true },
        AppInitService,
        {
            provide: APP_INITIALIZER,
            useFactory: initializeAppCall,
            deps: [AppInitService],
            multi: true
        }
    ],
```

Invalid provider for the NgModule 'AppModule' - only instances of Provider and Type are allowed, got: [..., ..., ..., ..., ..., ..., ..., ..., ..., ?[object Object]?

**Comment by ihssenedr** [comment]
Hi
same problem for me 
any solution please ?
