### ISSUE TITLE
Need for an update of the package "awesome-cordova-plugins/bluetooth-le" to the last version available 24 days before

### ISSUE THREAD

**Issue by Nickholas** [danielsogl/awesome-cordova-plugins#4310]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
The package @awesome-cordova-plugins/bluetooth-le is not updated with the last version of the cordova-plugin-bluetoothle 

**Expected behavior:**
Update to the last version if is it possible "cordova-plugin-bluetoothle": "^6.7.0",

**Steps to reproduce:**
Cant work with Android 12 because there is an issue with the new Permissions

**Related code:**

`this.bluetoothle.startScan({ services: [] }).subscribe((result) => {
      console.log(result);
      if (result.status === "scanResult") {
        const index = this.devices.findIndex( x => x.address == result.address);
        if (index == -1){
          this.onDeviceDiscovered(result);
        }
      }
    }, (error) => {
      this.scanError(error);
    });`

**Other information:**
I always get the same response when i try to do a scan():

Need android.permission.BLUETOOTH_SCAN permission for AttributionSource { uid = 10540, packageName = com.kaampo.precision, attributionTag = null, token = android.os.BinderProxy@2b60da, next = null }: GattService registerScanner

**Comment by nomadev** [comment]
created pull req with the fix: https://github.com/danielsogl/awesome-cordova-plugins/pull/4320

**Comment by Sampath-Lokuge** [comment]
We still have this error with the Capacitor 4 app. Any clue, please?

```
 "@awesome-cordova-plugins/core": "^6.2.0",
    "@capacitor/android": "^4.4.0",
    "@capacitor/app": "4.1.0",
    "@capacitor/core": "4.4.0",
    "@capacitor/haptics": "4.0.1",
    "@capacitor/keyboard": "4.0.1",
    "@capacitor/status-bar": "4.0.1",
    "@ionic/angular": "^6.1.9",
    "cordova-plugin-bluetoothle": "^6.7.0",

```
**Error**

>Scan error: Need android.permission.BLUETOOTH_SCAN permission for AttributionSource { uid = 10985, packageName = io.ionic.starter, attributionTag = null, token = android.os.BinderProxy@350f5ef, next = null }: GattService registerScanner

**Comment by jackhipson300** [comment]
We are also still getting this issue after updating to the latest version
