### ISSUE TITLE
Ionic 6 - FCM - plugin_not_installed when testing on real device

### ISSUE THREAD

**Issue by Souffiane** [danielsogl/awesome-cordova-plugins#4374]
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
I Can't get push token using fcm.getToken() when testing app in real android device.
It throws this error : plugin_not_installed.

```
import { FCM } from '@awesome-cordova-plugins/fcm/ngx';
...
  constructor(
    private platform: Platform,
    private fcm: FCM,
    private ionCompService: IonComponentService
  ) { }
  ngOnInit(): void {
    this.platform.ready().then(() => {
      this.fcm.getToken().then((token: string) => {
        this.backend.setPushToken(token);
      }, (err: any) => this.ionCompService.showErrorToast('setToken err : ' + err));
    });
  }
```

package.json :
```
    "@angular/common": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/forms": "^14.0.0",
    "@angular/platform-browser": "^14.0.0",
    "@angular/platform-browser-dynamic": "^14.0.0",
    "@angular/router": "^14.0.0",
    "@awesome-cordova-plugins/calendar": "^5.45.0",
    "@awesome-cordova-plugins/fcm": "^5.46.0",
    "@capacitor/core": "4.3.0",
    "@ionic-native/calendar": "^5.36.0",
    "@ionic-native/native-storage": "^5.36.0",
    "@ionic/angular": "^6.1.9",
    "@ionic/cordova-builders": "^7.0.0",
    "@ionic/storage-angular": "^3.0.6",
    "bootstrap": "^5.2.1",
    "cordova-android": "10.1.2",
    "cordova-browser": "6.0.0",
    "cordova-ios": "6.2.0",
    "ionicons": "^6.0.3",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
```

**Comment by fariskps** [comment]
same issue with cordova-plugin-biometric

**Comment by Souffiane** [comment]
I dropped this package...
I use instead https://github.com/dpa99c/cordova-plugin-firebasex and it works fine.

**Comment by arbassic** [comment]
Looks like some Cordova plugins are not working with the latest Ionic 6 libs... in my case InAppPurchases2 plug-in is not initialised well, and any action ends up with error "plugin_not_installed"

I tried to reinstall + npx cap sync, but with no success

**Comment by mkeology** [comment]
under the same spell on ionic6/Android with :

- cordova-plugin-purchase:13.1.5 
- @awesome-cordova-plugins/in-app-purchase-2": "^6.2.0",

calling  console.log(this.store.when('product')); results in

Native: tried calling InAppPurchase2.when, but the InAppPurchase2 plugin is not installed.
Install the InAppPurchase2 plugin: 'ionic cordova plugin add cordova-plugin-purchase'
error: "plugin_not_installed"

I tried to reinstall + npx cap sync, but with no success as well

**Comment by rodrigograca31** [comment]
> Looks like some Cordova plugins are not working with the latest Ionic 6 libs... in my case InAppPurchases2 plug-in is not initialised well, and any action ends up with error "plugin_not_installed"
> 
> I tried to reinstall + npx cap sync, but with no success


same here.

**Comment by YuChengLin817** [comment]
The following configuration works well for me with Ionic 6(6.20.8), FYR:

1)
npm install cc.fovea.cordova.purchase@10.5.3
npm install @ionic-native/in-app-purchase-2@5.36.0

2)
import {
  InAppPurchase2, 
  IAPError,
  IAPProduct,
  IAPProductOptions,
  IRefeshResult
} from '@ionic-native/in-app-purchase-2';
