### ISSUE TITLE
[question] how to build and debug changes locally?

### ISSUE THREAD

**Issue by ryaa** [danielsogl/awesome-cordova-plugins#4384]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
how can i debug/test the change when I make a fix or enhancement in one of the sub-packages of this repo? Ideally, i should be able to build and run ``npm link`` to be able to consume the required package in the app and test there, however, it seems, that there is a special publishing task and it is not possible to test/debug locally without publishing the package.

**Expected behavior:**
Be able to build and test the changes in a sub-package of this repo in the consuming app locally and before create a PR with a fix or enhancement

**Steps to reproduce:**
N/A

**Other information:**
N/A

**Comment by StefPler** [comment]
Having the same question, if anyone has any info on this it would be appreciated.

**Comment by malkodev** [comment]
I use this steps:

1. fork the official [@awesome-cordova-plugins](https://github.com/danielsogl/awesome-cordova-plugins) repository
2. make a fix in plugin
3. npm run build
4. copy directory with your plain from dist/@awesome-cordova-plugins/plugins/MY_PLUGIN to dist/@awesome-cordova-plugins/MY_PLUGIN your project
5. add package.json (copy from before version)

**Comment by StefPler** [comment]
@malkodev thanks for the response! Cloning the official repo has the plugins folder with all the cordova plug-ins but the folders only contain an index.ts file which is an interface. Do I add the files of the actual plug-in from its dedicated repo inside the `dist/@awesome-cordova-plugins/plugins/PLUGIN_I_WANT_TO_EDIT` and then try and build it?

For example for the IAB plug-in, should I take the files from https://github.com/apache/cordova-plugin-inappbrowser and place them in the `dist/@awesome-cordova-plugins/plugins/in-app-browser`

**Comment by ryaa** [comment]
> I use this steps:
> 
> 1. fork the official [@awesome-cordova-plugins](https://github.com/danielsogl/awesome-cordova-plugins) repository

I'm getting the error after the above step and running `npm install` to pull all the packages...
_Cannot find module '@awesome-cordova-plugins/core' or its corresponding type declarations.ts(2307)_

**Comment by ryaa** [comment]
> 5\. add package.json (copy from before version)

what if there is no before version?

**Comment by ryaa** [comment]
> I use this steps:
> 
> 1. fork the official [@awesome-cordova-plugins](https://github.com/danielsogl/awesome-cordova-plugins) repository
> 2. make a fix in plugin
> 3. npm run build
> 4. copy directory with your plain from dist/@awesome-cordova-plugins/plugins/MY_PLUGIN to dist/@awesome-cordova-plugins/MY_PLUGIN your project
> 5. add package.json (copy from before version)

This approach seems to be working. Thank you for the suggestions.

**Comment by Rosy503** [comment]
Hi all, I am upgrading my version from node14 to nodejs 16. When i am running npm run build 

it is showing me 

ETARGEt
no matching version found 
.....
..

can you please suggest a solution
