### ISSUE TITLE
Bug: TTS-advanced does not resolve properly

### ISSUE THREAD

**Issue by danielkleebinder** [danielsogl/awesome-cordova-plugins#4425]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
When using `tts.speak`, neither the `.then`, nor the `.catch` or `.finally` methods are invoked as expected.

**Expected behavior:**
The promise for the `tts.speak` function should be resolved properly.

**Steps to reproduce:**
Besides registering the `TextToSpeechAdvanced ` plugin in my `AppModule` providers, I injected it in my Angular `AppComponent`:

```typescript
import { Component, OnInit } from "@angular/core";
import { TextToSpeechAdvanced } from "@awesome-cordova-plugins/text-to-speech-advanced/ngx";

@Component({
  selector: "app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent implements OnInit {
  constructor(private tts: TextToSpeechAdvanced) {}

  ngOnInit(): void {
    // Ensure the device is ready with this timeout
    setTimeout(() => {
      this.tts.speak("Test")
        .then((r) => console.log("Resolved:", r))
        .catch((err) => console.warn("Rejected:", err))
        .finally(() => console.log("Finally"));
    }, 5_000);
  }
}
```
However, if I use [cordova-plugin-tts-advanced](https://www.npmjs.com/package/cordova-plugin-tts-advanced) directly, everything works as expected:

```typescript
import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent implements OnInit {
  ngOnInit(): void {
    // Ensure the device is ready with this timeout
    setTimeout(() => {
      (<any>window).TTS.speak("Test")
        .then((r) => console.log("Resolved:", r))
        .catch((err) => console.warn("Rejected:", err))
        .finally(() => console.log("Finally"));
    }, 5_000);
  }
}
```

**Other information:**
I have been using the following plugin and framework versions:
```
{
  ...
  "dependencies": {
    ...
    "@angular/core": "^12.2.16",
    "@awesome-cordova-plugins/text-to-speech-advanced": "^5.44.0"
    "cordova-plugin-tts-advanced": "^0.5.2",
    ...
  }
  ...
}
```
The platform where this issue occurred is `Android 10`.

**Comment by tkem** [comment]
I can confirm this issue. Please re-open!

**Comment by danielkleebinder** [comment]
@tkem Thank you for your response!

I have just investigated this issue a little further and it looks like the [`@awesome-cordova-plugins/text-to-speech-advanced`](https://www.npmjs.com/package/@awesome-cordova-plugins/text-to-speech-advanced) wrapper cannot handle promise-based Cordova APIs (yet). Around 5 years ago, the authors of [`cordova-plugin-tts-advanced`](https://www.npmjs.com/package/cordova-plugin-tts-advanced) migrated from a callback-based API to a promise-based one. Here is an example on what this looks like:

```js
exports.speak = function (text, onfulfilled, onrejected) {
  ...
};
```

became

```js
exports.speak = function (text) {
  return new Promise((resolve, reject) => {
    ...
  });
};
```

You can have [a look at the full diff here](https://github.com/spasma/cordova-plugin-tts-advanced/commit/dee3ea9ddb718ba0c428475664dc13f6cdb005eb). On the other hand, the [`@awesome-cordova-plugins/text-to-speech-advanced`](https://www.npmjs.com/package/@awesome-cordova-plugins/text-to-speech-advanced) wrapper still relies on the callback-based API [as you can see here](https://github.com/danielsogl/awesome-cordova-plugins/blob/master/src/%40awesome-cordova-plugins/plugins/text-to-speech-advanced/index.ts#L64).

```ts
@Cordova({
  successIndex: 1,  // << requires a success callback to be the second parameter of the API
  errorIndex: 2,    // << requires an error callback to be the third parameter of the API
})
speak(textOrOptions: string | TTSOptions): Promise<any> {
  return;
}
```

@danielsogl Are there any plans on updating this plugin wrapper in order to support promise-based Cordova APIs or would this involve too much effort?

@tkem For now I would suggest to use [`cordova-plugin-tts-advanced@0.4.2`](https://www.npmjs.com/package/cordova-plugin-tts-advanced/v/0.4.2) in order to be able to use the current version of the [`@awesome-cordova-plugins/text-to-speech-advanced`](https://www.npmjs.com/package/@awesome-cordova-plugins/text-to-speech-advanced) wrapper.

**Comment by danielkleebinder** [comment]
I have just consulted the ["Create Plugin Wrappers" documentation](https://github.com/danielsogl/awesome-cordova-plugins/blob/master/DEVELOPER.md) and found the `otherPromise` configuration option. Fixing the issue should look something like this if I am not mistaken:

```ts
@Cordova({
  otherPromise: true
})
speak(textOrOptions: string | TTSOptions): Promise<any> {
  return;
}
```

**Comment by tkem** [comment]
@danielkleebinder : Thanks for the quick analysis, looks promising!

**Comment by danielkleebinder** [comment]
@danielsogl Is this repository still active? Because this issue should not be closed if there even is a pull request that fixes it...
