### ISSUE TITLE
Zip Plugin Error by import in app.modules.ts

### ISSUE THREAD

**Issue by TheRealSharky** [danielsogl/awesome-cordova-plugins#4429]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
Error: Invalid provider for the NgModule 'AppModule' - only instances of Provider and Type are allowed, got: [..., ?[object Object]?]

**Expected behavior:**
Use the Zip plugin as expected.

**Steps to reproduce:**

**Related code:**
```
app.modules.ts
import { Zip } from '@awesome-cordova-plugins/zip/ngx';
and
providers: [ Zip, ... ]
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI : 6.20.4

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.14.2
   npm    : 8.5.0
   OS     : Windows 10
```

**Comment by shyamal890** [comment]
@TheRealSharky were you able to solve this?
