### ISSUE TITLE
Underlying NFC library is no longer being updated.

### ISSUE THREAD

**Issue by johanvanawesome** [danielsogl/awesome-cordova-plugins#4437]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**

The underlying NFC library is a phonegap library which has not been updated in over 2 years, despite several PRs completed. This causes problems because I am not able to fix bugs or submit necessary changes to this library.

**Expected behavior:**

The underlying NFC library should be actively maintained.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by nestra19** [comment]
I support this request, currently any android 12 will crash with this NFC library.

**Comment by mokmap** [comment]
It becomes problematic. Unable to use the NFC the application crashes immediately.

**Comment by GuppyDD** [comment]
Ich kehre zurück am 20.02.2023.

Sehr geehrte Damen und Herren,

vielen Dank für Ihre Nachricht. Derzeit befinde ich mich nicht im Büro, bin
jedoch ab dem 20.02.2023 wieder persönlich für Sie erreichbar. Ihre E-Mail
wird nicht weitergeleitet.

In dringenden Fällen wenden Sie sich bitte an meinen Kollegen Herrn Marcus
Kupke ***@***.***) oder die Zentrale unter: 0351 810 77 33, die Ihr
Anliegen an die entsprechende Fachabteilung weiterleiten wird.

Mit freundlichen Grüßen
Marco Gubisch


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[danielsogl/awesome-cordova-plugins] Underlying NFC library is no longer
being updated. (Issue #4437)" gesendet am 15.02.2023 01:05:25.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by seikosantana** [comment]
There is https://github.com/nerdy-harry/phonegap-nfc-api31 that has the fix, however, some methods are missing from awesome-cordova-plugins/nfc: i don't see any way to unregister ndef listeners.
