### ISSUE TITLE
Not found App Update.

### ISSUE THREAD

**Issue by marcelloinfoweb** [danielsogl/awesome-cordova-plugins#4453]
npm install @awesome-cordova-plugins/app-update --save-exact                                           
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@awesome-cordova-plugins%2fapp-update - Not found
npm ERR! 404 
npm ERR! 404  '@awesome-cordova-plugins/app-update@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by MaximBelov** [comment]
please use 
npm i @awesome-cordova-plugins/in-app-update

https://www.npmjs.com/package/@awesome-cordova-plugins/in-app-update

**Comment by marcelloinfoweb** [comment]
How to use? It has no tutorial.

**Comment by MaximBelov** [comment]
Check readme here
https://www.npmjs.com/package/cordova-in-app-update

**Comment by marcelloinfoweb** [comment]
Install both plugins?

**Comment by marcelloinfoweb** [comment]
> Check readme here https://www.npmjs.com/package/cordova-in-app-update

Install both plugins

**Comment by marcelloinfoweb** [comment]
Another question, is it possible to use it to download an apk file to be installed outside the Play Store?

**Comment by Lyfei** [comment]
> Another question, is it possible to use it to download an apk file to be installed outside the Play Store?

Have you tried it

**Comment by marcelloinfoweb** [comment]
> 



> > Another question, is it possible to use it to download an apk file to be installed outside the Play Store?
> 
> Have you tried it

No, there is no tutorial.
