### ISSUE TITLE
in-app-purchase-2 isn't compatible with latest version of cordova-plugin-purchase. Docs should be updated at minimum. 

### ISSUE THREAD

**Issue by tomingoglia** [danielsogl/awesome-cordova-plugins#4457]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
Regarding in-app-purchase-2
The current version of https://github.com/j3k0/cordova-plugin-purchase is 13.x. This has a breaking change from version 11. 11 seems to be the latest version that is supported by the capacitor **in-app-purchase-2** wrapper. The root of the window object has been changed for the newer version. It also looks like there may be other breaking changes.

**Expected behavior:**
Please update the plugin to support the latest version of the library or update the documentation to specify the latest compatible version. 
`npm install cordova-plugin-purchase@11`

**Steps to reproduce:**
Install without specifying version 11 will cause an exception that the Cordova plugin is not installed. 
`npm install cordova-plugin-purchase`

**Comment by websystems-dev** [comment]
Just to help someone in the same situation, I got it working in a **dirty** way. I'm using 
```
npm @awesome-cordova-plugins/onesignal@6.2.0 --force
npm cordova-plugin-purchase@11.0.0 --force
```
The --force option will install a theoretically uncompatible version of these plugins, so be careful and test it before to release.

**Comment by tomingoglia** [comment]
> Just to help someone in the same situation, I got it working in a **dirty** way. I'm using
> 
> ```
> npm @awesome-cordova-plugins/in-app-purchase-2@5.41.0 --force
> npm cordova-plugin-purchase@11.0.0 --force
> ```
> 
> The --force option will install a theoretically uncompatible version of these plugins, so be careful and test it before to release.

You shouldn't need --force. It will just force a download from the remote location vs, using your cached version. They key is to ensure that the capacitor plugin is compatible with the cordova plugin. As indicated, version 11 works. If you don't specify, the latests is pulled and that is version 13.x. All the examples on the Ionic site and around the web were built before version 13.

**Comment by neonish** [comment]
I'm getting the same error on iOS after updating cordova-plugin-purchase to v13.1.5:

```
⚡️  [warn] - Native: tried calling InAppPurchase2.when, but the InAppPurchase2 plugin is not installed.
⚡️  [warn] - Install the InAppPurchase2 plugin: 'ionic cordova plugin add cordova-plugin-purchase'
⚡️  [warn] - Native: tried calling InAppPurchase2.DEBUG, but the InAppPurchase2 plugin is not installed.
⚡️  [warn] - Install the InAppPurchase2 plugin: 'ionic cordova plugin add cordova-plugin-purchase'
```

**Comment by losciur** [comment]
Hi,
I have the same identical problem.
The only solution is to downgrade the plugin:
```
npm install @awesome-cordova-plugins/core@5.45.0
npm install cordova-plugin-purchase@11.0.0
npm install @awesome-cordova-plugins/in-app-purchase-2@5.45.0
```
I also have to downgrade `@awesome-cordova-plugins/core`.

**Comment by tomingoglia** [comment]
> Hi, I have the same identical problem. The only solution is to downgrade the plugin:
> 
> ```
> npm install @awesome-cordova-plugins/core@5.45.0
> npm install cordova-plugin-purchase@11.0.0
> npm install @awesome-cordova-plugins/in-app-purchase-2@5.45.0
> ```
> 
> I also have to downgrade `@awesome-cordova-plugins/core`.

@losciur, I've been able to successfully use @awesome-cordova-plugins (both core and in-app-purchase) version 6.2.0. Are you getting some other error using that latest version with version 11 of cordova-plugin-purchase?

**Comment by losciur** [comment]
Yes, I had an error that now I can't reproduce, but kind of incompatibility with the `@awesome-cordova-plugins/core` version, for that reason I downgrade all the plugins.
In any case, today I retried to uninstall e reinstall all the plugins and you're right, it's only necessary to downgrade cordova-plugin-purchase: `npm install cordova-plugin-purchase@11.0.0`.
Sorry for the previous bad post, and thanks!

**Comment by Schwankenson** [comment]
Ok, so there is no way to use in-app-purchase-2 with cordova-plugin-purchase 13 right now, correct?

**Comment by jjmhalew** [comment]
There is no way to use it right now. In-app-purchase-2 has to be updated with new methods such as initialize() as opposed to using refresh(). I gave it an attempt but it was quite challenging for me. I hope someone can update the wrapper for this plugin to be compatible with v13 soon

**Comment by oli-kester** [comment]
> Yes, I had an error that now I can't reproduce, but kind of incompatibility with the `@awesome-cordova-plugins/core` version, for that reason I downgrade all the plugins. In any case, today I retried to uninstall e reinstall all the plugins and you're right, it's only necessary to downgrade cordova-plugin-purchase: `npm install cordova-plugin-purchase@11.0.0`. Sorry for the previous bad post, and thanks!

I'm pretty new to the world of Android billing - but it seems to me that because v11 of this plugin uses the v4 of the Android billing library internally, Google won't let you publish any new apps that use this downgrade workaround? It gives me an error in the Google Play Console, saying that all new Android apps must use v5 of the Google Play Billing library.

**Comment by Schwankenson** [comment]
> There is no way to use it right now. In-app-purchase-2 has to be updated with new methods such as initialize() as opposed to using refresh(). I gave it an attempt but it was quite challenging for me. I hope someone can update the wrapper for this plugin to be compatible with v13 soon

I removed the in-app-purchase-2 and use only cordova-plugin-purchase 13. It is a bit more complex than with the angular wrapper, but I need to implement the new "offer" functionality in my app, to allow test periods for my subscriptions. And this is not supported by version 11.

**Comment by bboldi** [comment]
Will the wrapper be updated for v13 of the plugin - is that planned at all, or should we look for alternatives / use cordova pluin directly?

tnx

**Comment by j3k0** [comment]
I'm the author of the cordova plugin. Using it Cordova plugin directly is a good alternative. What exactly "awesome-cordova-plugins" added that made it simpler? Maybe this can be built directly into the plugin?

**Comment by j3k0** [comment]
OK, version 13 of `cordova-plugin-purchase` now being fully written in typescript, and it ships with type definitions, this should be less a necessity. Except if I'm missing something.

**Comment by jjmhalew** [comment]
> OK, version 13 of `cordova-plugin-purchase` now being fully written in typescript, and it ships with type definitions, this should be less a necessity. Except if I'm missing something.

@j3k0 I can confirm that version 13 works almost perfectly by itself using Ionic Angular with Capacitor! I had to read carefully through the wiki for any Typescript headsups. The only issue I experience is the timing of the initialization of the `CdvPurchase` object in `window` object. According to the documentation, we can use a event `deviceready` which Cordova has. However, by using Capacitor this event does not exist. My current workaround is verifying in an interval whether `window.CdvPurchase` is not undefined, and when it is defined I execute the rest of the code. I tried using Ionic's `Platform.ready()` as I thought it would be the equivalent, but the `window.CdvPurchase` object is still undefined then.

What is your recommendation as alternative to the `deviceready` event? Or does `cordova-plugin-purchase` need a custom event for this?

**Comment by j3k0** [comment]
Sorry I don't know what replaces `deviceready` on Capacitor. On Cordova, it's the event that's triggered once all plugins have been loaded. Capacitor should have something similar. If not, you can implement something like this:

```ts
function checkReady() {
  if (!window.CdvPurchase)
    setTimeout(checkReady, 100); // not loaded yet, check again in 100ms
  else
    deviceReady(); // plugin is available, call a "deviceReady()" function that you define.
}

checkReady(); // check if plugins are loaded already
```

**Comment by matheusdavidson** [comment]
Using ionic `this.platform.ready` seems to work for me:
```ts
constructor(private platform: Platform) {
    this.platform.ready().then(() => {
        const store: any = new window.CdvPurchase.Store();
        console.log('platform ready', store);
    });
}
```

Just not sure yet how to use the types but it's working.

**Comment by j3k0** [comment]
I think if you just import the plugin, you should have the types.

```ts
import "cordova-plugin-purchase"
```

**Comment by j3k0** [comment]
To summarize:

1. Install `"cordova-plugin-purchase"` directly with ` npm install cordova-plugin-purchase`, no need for `@awesome-cordova-plugins/in-app-purchase-2` anymore as the latest version includes typescript types.
2. `import "cordova-plugin-purchase"` in your code to get the typescript types.
3. Wait for ionic's `this.platform.ready` before initializing the plugin [[1]](https://github.com/danielsogl/awesome-cordova-plugins/issues/4457#issuecomment-1464223174).

**Comment by ptmkenny** [comment]
Ionic React and Vue don't have `this.platform.ready`, only Angular...

**Comment by ptmkenny** [comment]
In addition to providing TypeScript wrappers, `in-app-purchase-2` gives devs something to import so that the plugin can be used easily in React and other frameworks.  Cordova plugins aren't bundles so they can't be imported, right?

**Comment by spotvin42** [comment]
For me I don`t have any error to initialization but when uploading to Google Play, it says not compatible with BILLING VERSION 4. Is that related?

**Comment by HarelM** [comment]
I'm also maintaining another plugin which is referenced here, but the types are not up-to-date.
I simply instruct my users not to use this library as I didn't receive any feedback on how to fix the definitions here or how to send a PR to improve things. A bit pity, as I think this repo is very important, but I guess that the maintenance work here is overwhelming.
The best approach IMHO is to use the plugin's types if they exist...

**Comment by PiotrKula-ECO** [comment]
I am brand new to Ionic and this plugin and am struggling to follow the "new" way to use the plugin directly. With the wrapper I was getting

```
Native: tried calling InAppPurchase2.NON_RENEWING_SUBSCRIPTION, but the InAppPurchase2 plugin is not installed.
Install the InAppPurchase2 plugin: 'ionic cordova plugin add cordova-plugin-purchase'
```

I removed the wrapper trying to follow this but it seems like defining namespaces in module is highly frowned upon for some reason. I am tryin to import the types as I would normally in ngx/ts

```
import {CdvPurchase} from "cordova-plugin-purchase"
```
Gives an error the file is not a module - that takes me to articles about export and avoid using namespaces?


So just importing this in the file I want to manage payments
```
import "cordova-plugin-purchase"
import "cordova-plugin-purchase/www/store.d"
```
I then get an issue on my constructor saying it has no idea what CdvPurchase is. And to be honest I dont know if that is what I am supposed to be using. Aslo I am using Dependency Injection via Providers so will face the same issue

Are we supposed to import the store.d.ts in tsconfig.app.json?

**Comment by HarelM** [comment]
Here's a working example for anyone that needs it:
https://github.com/IsraelHikingMap/Site/blob/015d6780a2f9c08440ef51f18231ed81147af638/IsraelHiking.Web/src/application/services/purchase.service.ts

**Comment by ppumkin** [comment]
@HarelM Thank you for providing that example. I am making progress now. 

(I have also downloaded the app to have a play with it.. really cool! 👍👍)

**Comment by bebofit** [comment]
@HarelM how do you check if the subscription is expired? is it in unverified?

**Comment by HarelM** [comment]
I send a request to my server (with a user token) so that I know the user is authenticated, then the server sends iaptic server a request to see that the subscription is valid for that user.
If the server call completes I know the status, if the server request times out I keep the current state that is stored in the client until a proper connection is made to the server.
Hope that helps.
The code Iinked above has all the needed logic.

**Comment by bebofit** [comment]
so the .verified gets fired each time I open the app for all products? and we need to check it everytime? and I found a TO-DO about .unverified handling expired? @HarelM Thanks in advance

**Comment by HarelM** [comment]
Yea, this TODO was removed in latest version after I understood that I need my server call and can't use unverified callback:
https://github.com/IsraelHikingMap/Site/blob/7dc99dbd39be0070b737916bdcaf60068fa37667/IsraelHiking.Web/src/application/services/purchase.service.ts

**Comment by harryt2** [comment]
In my case it looks like it contains a "store-android.js" and "store-ios.js" instead of store.js 
![Screenshot 2023-10-06 at 2 16 13 PM](https://github.com/danielsogl/awesome-cordova-plugins/assets/12373916/c7363033-94b1-42ba-a39e-16e7cb127e6f)

**Comment by natmet** [comment]
Are test period avaliable with this plugin? in app purchases for apple?

**Comment by Schwankenson** [comment]
It`s available, I have it built in. But it is no fun to use it. I would try https://github.com/RevenueCat/purchases-capacitor if I had to built in purchase again.

**Comment by tolutronics** [comment]
> I send a request to my server (with a user token) so that I know the user is authenticated, then the server sends iaptic server a request to see that the subscription is valid for that user. If the server call completes I know the status, if the server request times out I keep the current state that is stored in the client until a proper connection is made to the server. Hope that helps. The code Iinked above has all the needed logic.

I don't think it includes restoring a purchase? @HarelM

**Comment by HarelM** [comment]
Unfortunately, I don't know what restoring a purchase means, and I think I don't have this use case in my app, so IDK...

**Comment by ptmkenny** [comment]
@HarelM [Restore purchases](https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/restoring_purchased_products) is required for all apps on iOS that use non-consumable IAP.  It's a pretty common requirement, and a reason for rejection during App Store review.

**Comment by matheusdavidson** [comment]
For anyone having trouble with payments on capacitor just use https://github.com/RevenueCat/purchases-capacitor

**Comment by alexp25** [comment]
Could someone explain the differences between using this wrapper and the current cordova plugin typescript wrapper? There seem to be differences in paradigm which are difficult to grasp. In this wrapper, there used to be events for product states (valid, invalid, approved, owned, etc.). In the cordova plugin wrapper these seem to be defined in different namespaces and not all events are documented.

**Comment by j3k0** [comment]
The wrapper used to be a typescript layer above the older version of this plugin. The newer version has been rewritten in typescript, so the wrapper is now unnecessary.

For paradigm difference, there's not so many, check the migration guide here: https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO:-Migrate-to-v13

**Comment by alexp25** [comment]
For example, I couldn't find information regarding the following scenarios that should be part of a fully functional implementation in production:
- how can I detect invalid products (and skip waiting for them to load their details - these need to be loaded from the store to display the actual prices)
- how can I extract the validation data (receipt, signature) to send it to my backend for validation (this validation data used to be provided in the product object)
- how can I detect when a purchase was canceled or there was some other error completing the purchase
- how can I detect when a purchase has been initiated, or requested (these used to be separate events from store.when())

**Comment by alexp25** [comment]
@j3k0 could you clarify if there are differences and how to address them, regarding my updated question above?

**Comment by j3k0** [comment]
@alexp25 You can check a full example here, hopefully that will answer your questions: https://github.com/j3k0/cordova-subscription-example/

**Comment by alexp25** [comment]
@j3k0 is there a similar demo but for products (consumable/non-consumable) instead of subscriptions? I could only find a demo that used braintree instead of In-App Purchase, which added to the confusion

**Comment by aershov24** [comment]
For React use this:

```js
import { Capacitor } from '@capacitor/core';
import 'cordova-plugin-purchase/www/store';

const subMonthly = 'test_sub';

const startStoreEventListeners = () => {
  if (Capacitor.isNativePlatform()) {
    document.addEventListener(
      'deviceready',
      async () => {    
        log.traceTag('startStoreEventListeners');

        const { store, ProductType, Platform } = window.CdvPurchase; // window is important
         
         store.register([{
            type: ProductType.PAID_SUBSCRIPTION,
            id: subMonthly,
            platform: Platform.GOOGLE_PLAY,
          }]);

          store.when()
              .productUpdated(() => {
                var mySub = store.get(subMonthly, Platform.GOOGLE_PLAY);
                log.traceTag('productUpdated', mySub);
              })
              .approved((p) => {
                log.traceTag('approved', p);
                p.finish();
              });

          store.initialize([Platform.GOOGLE_PLAY]);
        },
      false,
    );
  }
};

startStoreEventListeners();
...
```
