### ISSUE TITLE
docs needed

### ISSUE THREAD

**Issue by jcesarmobile** [danielsogl/awesome-cordova-plugins#4487]
In the readme the documentation section says this:

Documentation
For the full Awesome Cordova Plugins documentation, please visit https://ionicframework.com/docs/native/.

But Ionic docs were updated to show Capacitor plugins instead of Cordova plugins, so that link no longer shows information about your repository.

**Comment by nickstucko** [comment]
You can access the now-defunct documentation page via the Internet Archive:

https://web.archive.org/web/20220409152437/https://ionicframework.com/docs/native

FYI the above archive is from April 9, 2022. Not sure if this is the most elegant long-term solution, but it got me what I needed!

**Comment by jcesarmobile** [comment]
You can also still get them on the v5 version of the docs
https://ionicframework.com/docs/v5/native

**Comment by jcesarmobile** [comment]
I found https://danielsogl.gitbook.io/awesome-cordova-plugins/, which looks like official docs, I sent a PR using that.
The "home" page should be updated as it looks like some placeholder
