### ISSUE TITLE
[Diagnostic] Add Android support for requestBluetoothAuthorization()

### ISSUE THREAD

**Issue by dev04mst** [danielsogl/awesome-cordova-plugins#4500]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

Since  `cordova.plugins.diagnostic@7.0.0`  can finally support bluetooth permission request for **Android** too (and not just for iOS) I kindly ask if it is possible to fix it here too.

**Current behavior:**
The Promise returned by the function `Diagnostic.requestBluetoothAuthorization()` is rejected with error `Exception occurred: Value null at 0 of type org.json.JSONObject$1 cannot be converted to JSONArray` when called on Android platform

**Expected behavior:**
System dialog popup asking for Bluetooth permission

**Other information:**
[Commit link](https://github.com/dpa99c/cordova-diagnostic-plugin/commit/8f41fe7d7f3fa3f58c55d4c32ad02fcb19fa2b3a#diff-26e2138cb1a63e1018af2a6cb061d534c79f0a82cc1ef6eeeb89f04ef3bc3a98)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI       : 6.20.8
   Ionic Framework : @ionic/vue 6.5.1

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : 4.6.2
   @capacitor/core    : 4.6.2
   @capacitor/ios     : 4.6.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.13.0
   npm    : 8.19.3
   OS     : Windows 10
```

**Comment by dariobertini** [comment]
Any news about this?

**Comment by GerardoTovar** [comment]
I am currently using the plugin and have the same problem. Is there any solution

**Comment by RubioN** [comment]
I have the same issue
