### ISSUE TITLE
Tealium dataLayer is not properly transmitted

### ISSUE THREAD

**Issue by benthieu** [danielsogl/awesome-cordova-plugins#4513]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
Tracking or adding data does not properly submit the dataLayer to the native cordova plugin. I think the problem occurs because the type `Map<string, any>` does not translate to the expected object `{'key': value}` which is expected by the cordova plugin.
In the application console (i.e. xcode) the dataLayer is always empty:
```
To Native Cordova ->  TealiumCordova track INVALID ["options": [{
    dataLayer =     {
    };
    type = view;
    viewName = "screen_view";
}]]
```

**Expected behavior:**
dataLayer to not be empty.

**Steps to reproduce:**
Track something or add data with the typescript/ionic wrapper.

**Related code:**
An adaption like this could resolve the issue:
```
export declare type Data = {
  [key: string]: any;
};
export interface TealiumDispatch {
    dataLayer: Data;
    type: string;
    toJson(): string;
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 6.20.8
   Ionic Framework               : @ionic/angular 6.5.6
   @angular-devkit/build-angular : 15.2.0
   @angular-devkit/schematics    : 15.2.0
   @angular/cli                  : 15.2.0
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : 4.7.0
   @capacitor/core    : 4.7.0
   @capacitor/ios     : 4.7.0

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : ios 6.2.0

System:

   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v16.15.0
   npm               : 8.5.5
   OS                : macOS Unknown
   Xcode             : Xcode 14.2 Build version 14C18
```

**Comment by benthieu** [comment]
@danielsogl Would it help if we proposed a PR?

**Comment by Spinnenzunge** [comment]
@danielsogl Can you please reopen this issue as this is still a problem
