### ISSUE TITLE
unable to resolve dependency with rxjs

### ISSUE THREAD

**Issue by loicparent** [danielsogl/awesome-cordova-plugins#4538]
**I'm submitting a ...**
bug report

**Current behavior:**
Hello,
I am updating the packages of my ionic project but I encounter some issues with the plugins of `@ionic-native`.
When I try to install a package, I got this error for each package of `@ionic-native`:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: totemus@0.0.1
npm ERR! Found: rxjs@7.8.1
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"^7.8.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^5.5.0 || ^6.5.0" from @ionic-native/core@5.36.0
npm ERR! node_modules/@ionic-native/core
npm ERR!   @ionic-native/core@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Expected behavior:**
I should install or update a package without using `--legacy-peer-deps`.

**Steps to reproduce:**
1. Install a fresh install of Ionic
2. Install a package of Ionic Native (ex: `npm install @ionic-native/core`).
3. See the error

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 7.0.1 (/Users/my-username/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.4
   @angular-devkit/build-angular : 15.2.7
   @angular-devkit/schematics    : 15.2.7
   @angular/cli                  : 15.2.7
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.8.0
   @capacitor/android : 4.8.0
   @capacitor/core    : 4.8.0
   @capacitor/ios     : 4.8.0

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   ios-sim : 8.0.2
   NodeJS  : v16.15.0 (/Users/my-username/.nvm/versions/node/v16.15.0/bin/node)
   npm     : 8.19.2
   OS      : macOS Unknown
   Xcode   : Xcode 14.3 Build version 14E222b
```

Thanks for your help :)
_Loïc_

**Comment by malte94** [comment]
Yes, pretty annoying. This issue exists for a longer time now.

To fix it, just add rxjs as a package to the project. The most recent version works fine.

`npm i rxjs`

**Comment by picheli20** [comment]
Same issue here I've been trying to fix with some previous versions, but no luck... 

@malte94 `7.8.1` is the latest version

**Comment by Sampath-Lokuge** [comment]
You need to migrate those plugins to the awesome Cordova plugins. Then no issues.

Ref: https://github.com/ionic-team/ionic-framework/issues/27436#issuecomment-1540512948

**Comment by Sampath-Lokuge** [comment]
Yes, you need to migrate all the ionic native plugins to awesome. Then no issues. i.e. no more Ionic natives now.

Ref: https://ionic.io/blog/a-new-chapter-for-ionic-native

**Comment by malte94** [comment]
Ah, I understand. I personally have never used Ionic native plugins. Either awesome-cordova-plugins, or Capacitor. I think that TO uses @ionic-native, so it could possibly fix the issue for him 👍

**Comment by Sampath-Lokuge** [comment]
Yes!
