### ISSUE TITLE
How to properly test an application with cordova-plugin-purchase with capacitor?

### ISSUE THREAD

**Issue by rprokopenko** [danielsogl/awesome-cordova-plugins#4578]
I have question, how to properly test an application with cordova-plugin-purchase with capacitor?

I did all the steps uploaded aab in Google Play Console in closed testing, added testers, added products and activated them. And now the question, I have to always upload a new version in Google Play Console to test and wait 2 hours for the app to be reviewed? Or is there some other method to test locally?

Thanks for the answer!

**Comment by kurtiev** [comment]
Hi @rprokopenko.

Use Internal testers, it's not needed to wait for review.
Closed - I believe it's external users, which are not listed in your Testers (QA) group in Play Console. 


p.s. 
It's rather a question to the Stackoverflow :) 

<img width="293" alt="image" src="https://github.com/danielsogl/awesome-cordova-plugins/assets/15800725/ce3d06d7-9449-4fb8-97ae-736d37e70645">
