### ISSUE TITLE
update the pacakge to rxjs@7.8.1

### ISSUE THREAD

**Issue by alex5956** [danielsogl/awesome-cordova-plugins#4583]
hi i have a problem with ionic-native permission
the bug is :+1: ```
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^5.5.0 || ^6.5.0" from @ionic-native/android-permissions@5.36.0
npm ERR! node_modules/@ionic-native/android-permissions
npm ERR!   @ionic-native/android-permissions@"^5.36.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: rxjs@6.6.7
npm ERR! node_modules/rxjs
npm ERR!   peer rxjs@"^5.5.0 || ^6.5.0" from @ionic-native/android-permissions@5.36.0
npm ERR!   node_modules/@ionic-native/android-permissions
npm ERR!     @ionic-native/android-permissions@"^5.36.0" from the root project

could you update the package please ?to rxjs@7.8.1
cordially

**Comment by alex5956** [comment]
?

**Comment by alex5956** [comment]
hello , coud you do it ??

**Comment by codoffer** [comment]
Can you update rxjs version?

**Comment by SheriffOladejo** [comment]
did you find a solution to this?

**Comment by codoffer** [comment]
> did you find a solution to this?

We haven't got any reply. We have decided to use other packages - 
https://github.com/perfood/capacitor-healthkit
https://github.com/perfood/capacitor-google-fit
