### ISSUE TITLE
Update "purchases" (currently using 3.2.1) to latest version of cordova-plugin-purchases (4.3.0)

### ISSUE THREAD

**Issue by NicoHof** [danielsogl/awesome-cordova-plugins#4607]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request / version update request
- [ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
@awesome-cordova-plugins/purchases is the recommended capacitor wrapper from revenueCat https://www.revenuecat.com/docs/ionic 

The latest version of cordova-plugin-purchases is 4.3.0 which support Google Billing Library 5 already. (https://github.com/RevenueCat/cordova-plugin-purchases/releases/tag/4.3.0)
Would be important that @awesome-cordova-plugins/purchases uses the latest version of the cordova plugin. (currently using 3.2.1) 

**Expected behavior:**
Update dependency and support to latest version 4.3.0

**Steps to reproduce:**
Follow official installation guide: https://www.revenuecat.com/docs/ionic

```
// Install Cordova plugin
npm install cordova-plugin-purchases

// Install Ionic Native core library (once per project)
npm install @awesome-cordova-plugins/core --save

// Install TypeScript wrapper
npm install @awesome-cordova-plugins/purchases

// Update native platform project(s) to include newly added plugin
ionic cap sync
```

**Comment by NicoHof** [comment]
@vegaro Maybe you can give some information about this topic, since you did the last version update? 🙏

**Comment by vegaro** [comment]
We are currently working on a capacitor plugin and are going to focus our engineering efforts on that. We need to update the installation docs, since they are wrong as you pointed out. Will the new capacitor plugin work for you, or do you still need the`@awesome-cordova-plugins/purchases` to be updated?

**Comment by NicoHof** [comment]
@vegaro I am not using this plugin (because its not up to date) neither the other one you mentioned (this one, right? https://github.com/RevenueCat/purchases-capacitor/tree/main) since it does not have all features, too and the installation guide link is not working (https://github.com/RevenueCat/purchases-capacitor/issues/86).

Currently I am using the cordova plugin without any wrapper directly like this:

```js
import PurchasesNative, {
    PurchasesOfferings, // types for TS
} from 'cordova-plugin-purchases/www/plugin';

PurchasesNative.configureWith({
    apiKey,
    appUserID,
});

PurchasesNative.getOfferings((res) => {...}, (err) => {...})
```

are there any downsides aside from the callbacks you have to use instead of the promises?

I had some time consuming trouble with the integration since the docs point to this plugin which is not up to date.
IMHO it really should be mentioned and explained which options you have for ionic/capacitor here: 
https://www.revenuecat.com/docs/ionic

**Comment by DiogoParrinha** [comment]
In my case, a Capacitor plugin is exactly what I would need.

Right now I'm using the wrapper and it works well, but it's lacking the new
features/API.

Thanks!

**Comment by mepc36** [comment]
> We are currently working on a capacitor plugin and are going to focus our engineering efforts on that. We need to update the installation docs, since they are wrong as you pointed out. Will the new capacitor plugin work for you, or do you still need the`@awesome-cordova-plugins/purchases` to be updated?

@vegaro I still need `@awesome-cordova-plugins/purchases` to be updated please. The deadline is coming up and I need some time to, at the very least, switch over to using `cordova-plugin-purchases`.

Please advise when you get a second, thank you!

**Comment by mepc36** [comment]
After examining the available package for purchases on Capacitor (`cordova-plugin-purchase`), I am upping the desperation here, from a "humble request" to "urgent supplication", lol. That's because the official Capacitor plugin for purchases, `cordova-plugin-purchase`, is a very difficult library to work with. I implemented it a few months back before replacing it with this one, and haven't looked back since. `cordova-plugin-purchase` has a very odd, non-intuitive event-based API for fetching products. Here's a micro-example:

https://purchase.cordova.fovea.cc/discover/micro-example

```
document.addEventListener('deviceready', onDeviceReady);

var myProduct;

function onDeviceReady() {
  const {store, ProductType, Platform} = CdvPurchase;
  refreshUI();
  store.register([{
    type: CdvPurchase.CONSUMABLE,
    id: 'my_product',
    platform: Platform.TEST,
  ]});
  store.when()
    .productUpdated(refreshUI)
    .approved(finishPurchase);
  store.initialize([Platform.TEST]);
}

function finishPurchase(p) {
  localStorage.goldCoins = (localStorage.goldCoins | 0) + 10;
  p.finish();
  refreshUI();
}

function refreshUI() {
  const {store, ProductType, Platform} = CdvPurchase;
  myProduct = store.get('my_product', Platform.TEST);
  const myTransaction = store.findInLocalReceipts(myProduct);
  const button = `<button onclick="myProduct.getOffer().order()">Purchase</button>`;

  document.getElementsByTagName('body')[0].innerHTML = `
  <div>
    <pre>
      Gold: ${localStorage.goldCoins | 0}

      Product.state: ${myTransaction ? myTransaction.state : ''}
             .title: ${myProduct ? myProduct.title : ''}
             .descr: ${myProduct ? myProduct.description : ''}
             .price: ${myProduct ? myProduct.pricing.price : ''}

    </pre>
    ${myProduct.canPurchase ? button : ''}
  </div>`;
}
```

Waiting for events to be emitted inside `.when` methods made debugging hell, when everything could be a race condition. In comparison, here is a micro-example for this library:

https://www.revenuecat.com/docs/ionic#react

```
import { Purchases } from '@awesome-cordova-plugins/purchases';

const Tab1: React.FC = () => {
  Purchases.setDebugLogsEnabled(true);
  Purchases.purchases.configureWith({
    apiKey: "my_api_key",
    appUserID: "my_app_user_id"
  });
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Tab 1</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent>
        <IonButton onClick={openScanner}>Scan barcode</IonButton>
      </IonContent>
    </IonPage>
  );
};
```

...and then I can just do this:

```
          const offerings = await Purchases.getOfferings();
          setOfferings(offerings)
          const customerInfo = await Purchases.getCustomerInfo()
          setCustomerInfo(customerInfo)
```

This is awesome, since I can just await the async action!

@vegaro I'd be willing to help out on this too, if you need the dev resources. Please let us know, thank you!

**Comment by mepc36** [comment]
Also it seems like `capacitor-purchases` is not full-featured, and also not fully owned by RevenueCat yet:

https://github.com/RevenueCat/purchases-capacitor/issues/78
https://github.com/RevenueCat/purchases-capacitor/issues/80

I'm certainly not suggesting that you guys support this plugin forever, but it IMHO it's a necessary bridge to the next generation of Capacitor-specific plugins.

**Comment by DiogoParrinha** [comment]
@mepc36 could it be that they're working on a different Capacitor plugin though? I definitely agree it would be a huge transformation. The current approach is very easy to use

**Comment by vegaro** [comment]
The Capacitor plugin we are working on is still internal and we are trying to make it public asap. We'll make it public very soon (in the next weeks). We want to make sure it's fully featured and well tested.

I'm sorry the documentation in the website is wrong and still suggesting to use the awesome-cordova-plugin. I'll make sure that gets removed since the latest version is not compatible. It was an oversight.

**Comment by mepc36** [comment]
Great thanks @vegaro !

**Comment by vegaro** [comment]
I just fixed the docs in https://www.revenuecat.com/docs/ionic. I removed any reference to awesome-cordova-plugins and changed it do something similar https://github.com/danielsogl/awesome-cordova-plugins/issues/4607#issuecomment-1683604024 . This is of course temporary until we have the Capacitor plugin, where we will just point to install that one instead

**Comment by mepc36** [comment]
Awesome thanks @vegaro! Really great.

Any update on a release date for that Capacitor plugin?

**Comment by vegaro** [comment]
We are ultimating internal review @mepc36 and we are close to shipping a beta this week 🥳 I will post here whenever that happens

**Comment by mepc36** [comment]
> We are ultimating internal review @mepc36 and we are close to shipping a beta this week 🥳 I will post here whenever that happens

Awesome thank you @vegaro ! Congrats on getting to beta testing and good luck 👍

**Comment by tonidero** [comment]
Hi everyone! Heads up that the first beta of the capacitor plugin has been released! https://www.npmjs.com/package/@revenuecat/purchases-capacitor. Please check it out and let us know if you run into any issues or if you have any questions. We will finish the public documentation soon, so it's easier to implement.

**Comment by aboedo** [comment]
We had originally opted not to have mocked values to avoid having mock data in a production app. 

Perhaps we can find a middleground to make development easier

**Comment by tonidero** [comment]
Hi @woutersteven2020, we added `setMockWebResults` to the plugin in `6.0.0-beta.2` that allows the promises to resolve with some mock data. Please let us know if that works for you!

**Comment by mepc36** [comment]
I started a quick and dirty migration guide for this in the "Issues" section of the @revenuecat/capacitor-purchases project @vegaro 

Feel free to propagate if you feel it'd be helpful to your users, thanks!

**Comment by vegaro** [comment]
We've opened a PR against this repository to update to cordova-plugin-purchases 5.0.0 https://github.com/danielsogl/awesome-cordova-plugins/pull/4658. Not sure if the PR will ever get merged, it doesn't look like they are merging many PRs lately. But you can probably point to the branch in the meantime.

Heads up, we are focusing our efforts on Capacitor and the last release of this repository is from almost a year ago so this is probably going to be the last time we update the wrapper. We've updated so it's easier for devs to update to the latest versions of the cordova-plugin-purchases plugin, specially to comply with Play Store's billing client version requirements.
