### ISSUE TITLE
not found keychain-touch-id same like @ionic-native/keychain-touch-id

### ISSUE THREAD

**Issue by ipehimanshu** [danielsogl/awesome-cordova-plugins#4627]
Hello

does any one help me to get @ionic-native/keychain-touch-id based on awesome-cordova-plugins

Thank you

**Comment by nbadiganti** [comment]
Following, I can raise a PR if required.

**Comment by Akash-Tapadia-DFT** [comment]
Did we have any update on this? I couldn't find the wrapper for keychain-touch-id plugin
