### ISSUE TITLE
Android 13 API 33 : Camera/Gallery doesn't open 

### ISSUE THREAD

**Issue by Nandhinimahadev** [danielsogl/awesome-cordova-plugins#4629]
Issue:

The camera doesn't open, Gallery doesn't open, for the Android 13 emulator
Pointing API 33 of Android in the build.gradle

What is expected to happen?
Camera should open, Gallery should open

Environment, Platform, Device
Ionic, Android 13

**Comment by kiwikia** [comment]
@Nandhinimahadev I think we are having a similar / the same issue, have you discovered anything new on the issue since you raised it?

**Comment by Nandhinimahadev** [comment]
@kiwikia  We have similar issue but answer still not found that is not working for me

**Comment by Toeler** [comment]
This is fixed in https://github.com/apache/cordova-plugin-camera/pull/844, update `cordova-plugin-camera` to >= 7.0.0 (not yet on NPM, waiting on https://lists.apache.org/thread/gcvv0zf1rs1svvdv9pjffwdwx7yn69fd to complete)

**Comment by Nandhinimahadev** [comment]
@Toeler  thanks let me check

**Comment by CrmSupport-AbacusDesk** [comment]
please help me image picker not working in android 13.

**Comment by RaccoonFive** [comment]
We have the same issue in our app on up to date android devices. 
Any workaround would be really helpful!
