### ISSUE TITLE
Error at npm run build

### ISSUE THREAD

**Issue by abutizi** [danielsogl/awesome-cordova-plugins#4630]
**I'm submitting a ...**  (check one with "x")
- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
I'm getting an error when I run "npm run build"

**Expected behavior:**
Build smoothly, so that I can use the wrapper for my ionic project.

**Steps to reproduce:**
Download this repo as zip. Open it with command line. Run "npm i " then afterwards run "npm run build".

**Related code:**

```
insert any relevant code here

error: Error transforming method: restart
error: Cannot read properties of undefined (reading 'kind')

MY_PATH\awesome-cordova-plugins-master\node_modules\typescript\lib\typescript.js:83925
            return !!(node.transformFlags & 2048 /* ContainsTypeScriptClassSyntax */);
TypeError: Cannot read properties of undefined (reading 'transformFlags')

MY_PATH\awesome-cordova-plugins-master\node_modules\typescript\lib\typescript.js:83925:28)

MY_PATH\awesome-cordova-plugins-master\node_modules\typescript\lib\typescript.js:83925
            return !!(node.transformFlags & 2048 /* ContainsTypeScriptClassSyntax */);

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kartikthakur2022** [comment]
I also need updated plugins available in the master branch for Android 13 compatibility. Donot know when they will publish new version from master

**Comment by abutizi** [comment]
I think they will do it in Christmas.
JK. lets hope they keep this updated.

**Comment by bbl-jcastaneda** [comment]
Hi, delete the conflicting plugin folder called diagnostic and run rpm run build once more. That should solve the issue. I was able to build after that.
