### ISSUE TITLE
Support for cordova-plugin-camera 7.0 api 33 Android

### ISSUE THREAD

**Issue by rbenedettix** [danielsogl/awesome-cordova-plugins#4640]
I was using this package in my capacitor 5 project but with new Android API 33 camera stopped working.
As far as i know the problem is solved with cordova-plugin-camera 7.0.

I tried implementing cordova-plugin-camera 7.0 directly but it gives me an error like this:
Error: Module not found: Error: Can't resolve 'cordova-plugin-camera'

My import is:
import "cordova-plugin-camera"

Is there any plan to solve the issue with awesome-cordova-plugin too?

Edit: obviously i runned npm install with the correct version of cordova-plugin-camera and i checked node-modules to be sure the file was there

Thanks

**Comment by RaccoonFive** [comment]
We also have this issue preventing our users from taking pictures on up to date android devices.

Any workarounds would be really helpful!

**Comment by donmb1** [comment]
same here +1

**Comment by rbenedettix** [comment]
In the end, our workaround was to change the plugin and use the Capacitor plugin. We did not find any other alternatives.

**Comment by donmb1** [comment]
yes I did the same and it works now
