### ISSUE TITLE
lack of iOS 17 support

### ISSUE THREAD

**Issue by mkocik** [danielsogl/awesome-cordova-plugins#4643]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
After upgrading system to ios17 calendar plugin stopped working. It doesn't ask about permissions and it doesn't write any data to user's calendar.

**Expected behavior:**
In ios16 (and earlier) calendar plugin asks about write permissions & allows app to create new calendar instances / add them to user's system's calendar

**Other information:**
requestReadWritePermission returns empty error

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Ionic:

   Ionic CLI                     : 7.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.9
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.3.7
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.3) : 1.7.1

System:

   NodeJS : v16.20.0 (/usr/local/Cellar/node@16/16.20.0/bin/node)
   npm    : 8.19.4
   OS     : macOS 14.0 (23A344)
```

**Comment by matfantinel** [comment]
I'm also facing this. Seems like it's because of the [changes in iOS 17 highlighted here](https://developer.apple.com/documentation/technotes/tn3153-adopting-api-changes-for-eventkit-in-ios-macos-and-watchos).

I've tried adding `NSCalendarsFullAccessUsageDescription` to my Info.plist but that wasn't enough, as it seems the actual native functions to call have changed.

**Comment by gatelli** [comment]
+1, doesn't find any calendars also.

**Comment by matfantinel** [comment]
There is this open PR on the plugin's repo that claims to fix the issue: https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/pull/566

Might be worth moving the discussion to the issue in that repo as well: https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/565

**Comment by mkocik** [comment]
Yes I tested it initially and it works on iOS17. But not on the older versions 😞  I proposed a simple fix to keep the backward compatibility. 

Once we have it merged and released in PhoneGap-Plugin, we will need to bump the version here and release it also.

In a meantime, for testing purposes, you can open the `Pods/Development Pods/CordovaPlugins/CordovaPluginCalendar/Calendar.md` in Xcode and just replace a content of `initEventStoreWithCalendarCapabilities` method with the one from [this PR](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/pull/566/files).
