### ISSUE TITLE
@awesome-cordova-plugins/calendar - calendar access has changed in iOS 17

### ISSUE THREAD

**Issue by pkings** [danielsogl/awesome-cordova-plugins#4656]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**

In iOS 17, the api for requesting calendar access has changed: https://developer.apple.com/documentation/technotes/tn3152-migrating-to-the-latest-calendar-access-levels

"Replace the deprecated request methods. The iOS, macOS, and watchOS SDKs bundled in Xcode 15 deprecate the [requestAccess(to:completion:)](https://developer.apple.com/documentation/eventkit/ekeventstore/1507547-requestaccess) and [requestAccess(to:)](https://developer.apple.com/documentation/eventkit/ekeventstore/1507547-requestaccess) methods. If your app links against the iOS 17 SDK, macOS 14 SDK, or watchOS 10 SDK, calling these deprecated request methods doesn’t prompt the user for access and throws an error message. Remove these methods from your app. Use the new APIs to prompt the user for access in your app:"

As indicated in the quote above, the user prompt for asking for calendar access does not show up anymore.

**Expected behavior:**
In iOS Versions below 17, requesting the calendar access worked using ``requestReadPermission(): Promise<any>``. It should also work in iOS 17.

**Steps to reproduce:**
Try to request calendar access using ``requestReadPermission(): Promise<any>`` of ``import {Calendar} from "@awesome-cordova-plugins/calendar/ngx";``

Thanks! :-)

**Comment by mdivya-symplr** [comment]
@pkings  For me this I'm on capacitor. Adding  `NSCalendarsFullAccessUsageDescription` to `Info.plist` has worked. After this I'm receiving calendar permissions.
