### ISSUE TITLE
SMS is not compatible with Angular Ivy

### ISSUE THREAD

**Issue by ivopashov** [danielsogl/awesome-cordova-plugins#4713]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
Hey, just created a fresh IONIC app and I try using the SMS plugin but get

```
g]   node_modules/@awesome-cordova-plugins/sms/ngx/index.d.ts:40:22
[ng]     40 export declare class SMS extends AwesomeCordovaNativePlugin {
[ng]                             ~~~
[ng]     This likely means that the library (@awesome-cordova-plugins/sms/ngx) which declares SMS is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
[ng] 

```

I also run latest angular/ionic/sms plugin:

```
    "@angular/core": "^17.0.2",
    "@ionic/angular": "^7.0.0",
    "@capacitor/core": "5.6.0",
    "@awesome-cordova-plugins/core": "^6.6.0",
    "@awesome-cordova-plugins/sms": "^6.6.0",
```

**Expected behavior:**
SMS plugin works

**Steps to reproduce:**
Nothing specific. Try install and import the SMS plugin.

**Related code:**

```
N/A
```

**Other information:**
-

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.3
   @angular-devkit/build-angular : 17.0.9
   @angular-devkit/schematics    : 17.0.9
   @angular/cli                  : 17.0.9
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v20.10.0 (/usr/local/bin/node)
   npm    : 10.2.3
   OS     : macOS Unknown
```

**Comment by johndoeetfils** [comment]
J'ai le même problème sur tous les @awesome-cordova-plugins !!!

**Comment by GerardoTovar** [comment]
I have the same problem..Try with SMSOriginal and SMS ...Error: export 'SMSOriginal' (imported as 'SMSOriginal') was not found in '@awesome-cordova-plugins/sms' (possible exports: SMS)
