### ISSUE TITLE
Wrong top package.json field 'main' 

### ISSUE THREAD

**Issue by snowwolfjay** [danielsogl/awesome-cordova-plugins#4714]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
the "main" field value is "bundle.js", but there are no bundle.js

**Expected behavior:**
"main" field should be "index.js" , unlike the sub ngx ( there is a bundle.js)

**Steps to reproduce:**
no need produce, just can see the bundle.js not exist 

**Related code:**

```
 "description": "Awesome Cordova Plugins - Native plugins for ionic apps",
    "main": "bundle.js",    // ******* the main folder has no such file, should be index.js
    "module": "index.js",
    "typings": "index.d.ts",
    "author": "ionic",
    "license": "MIT",
    "repository": {
        "type": "git",
        "url": "https://github.com/danielsogl/awesome-cordova-plugins.git"
    },
    "name": "@awesome-cordova-plugins/android-permissions",
    "dependencies": {
        "@types/cordova": "latest"
    },
    "peerDependencies": {
        "rxjs": "^5.5.0 || ^6.5.0 || ^7.3.0",
        "@awesome-cordova-plugins/core": "^6.0.1"
    },
    "version": "6.6.0"
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by dsteinel** [comment]
Same for me. This creates issues when running vitest. 
I have setup an Ionic project with vite + vitest. When I want to test a file which imports e.g. the barcode-scanner it gives me the error: `Error: Failed to resolve entry for package "@awesome-cordova-plugins/barcode-scanner". The package may have incorrect main/module/exports specified in its package.json.` . I can confirm that changing the "bundle.js" to "index.js" in the main field of the package.json resolves the issue.
