### ISSUE TITLE
Exception calling Diagnostic.requestBluetoothAuthorization method

### ISSUE THREAD

**Issue by SidiBecker** [danielsogl/awesome-cordova-plugins#4739]
**I'm submitting a ...** 
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use the discussions section https://github.com/danielsogl/awesome-cordova-plugins/discussions

**Current behavior:**
Calling `Diagnostic.requestBluetoothAuthorization()`, the promise is rejecting with error` Exception occurred: Value null at 0 of type org.json.JSONObject$1 cannot be converted to JSONArray` on Android platform.

**Expected behavior:**
System asking for Bluetooth permission successfully

**Steps to reproduce:**
Just call the `Diagnostic.requestBluetoothAuthorization()` on Android

**Related code:**
https://github.com/dpa99c/cordova-diagnostic-plugin/commit/8f41fe7d7f3fa3f58c55d4c32ad02fcb19fa2b3a#diff-504fb4a76cceae499fd94d8dc5db6830c1893f7de73e3861a02af2edca11beecR237

**Other information:**
Using the follow code, the plugin works:
```
 cordova.plugins.diagnostic.requestBluetoothAuthorization((s) => {
         //success behavior
      }, (e) => {
        //errorbehavior
      }, 
      [] //With permissions param
);
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 7.0.1 (C:\Users\s275\AppData\Roaming\nvm\v16.20.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.0.12
   @angular-devkit/build-angular : 15.2.5
   @angular-devkit/schematics    : 15.2.5
   @angular/cli                  : 15.2.5
   @ionic/angular-toolkit        : 9.0.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 12.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 40 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.20.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.4
   OS     : Windows 10
```

**Comment by bcastro-mcm** [comment]
I can fixed.
This error appears in version 7.1.4.
Modify the function `requestBluetoothAuthorization()` in file Diagnostic_Bluetooth.java

SOLUTION HERE:

`

    public void requestBluetoothAuthorization(JSONArray args, CallbackContext callbackContext) throws Exception {
        JSONArray permissionsToRequest = new JSONArray();

      if (args.length() > 0 && !args.isNull(0)) {
        Object firstArg = args.get(0);

        // Check if the first argument is actually a JSONArray
        if (firstArg instanceof JSONArray) {
          JSONArray specifiedPermissions = (JSONArray) firstArg;
          if (specifiedPermissions.length() > 0) {
            for (int i = 0, size = specifiedPermissions.length(); i < size; i++) {
              String specifiedPermission = specifiedPermissions.getString(i);
              if (contains(permissions, specifiedPermission)) {
                permissionsToRequest.put(specifiedPermission);
              }
            }
          }
        } else {
          // Handle the case where the first argument is not a JSONArray
          // For instance, you could log an error or take some default action
          // Here we simply log an error
          Log.e("Error", "Expected a JSONArray but got something else.");
        }
      } else {
        // If no valid JSONArray is provided, use all permissions
        for (String permission : permissions) {
          permissionsToRequest.put(permission);
        }
      }

        Diagnostic.instance._requestRuntimePermissions(permissionsToRequest, Diagnostic.instance.storeContextByRequestId(callbackContext));

        PluginResult result = new PluginResult(PluginResult.Status.NO_RESULT);
        result.setKeepCallback(true);
        callbackContext.sendPluginResult(result);
    }


`
