### ISSUE TITLE
Where is @ionic-native/sqlite in awesome-cordova-plugins?

### ISSUE THREAD

**Issue by Madserker** [danielsogl/awesome-cordova-plugins#4748]
Hello,
We've been using in our project the library **@ionic-native/sqlite** from the npm: https://www.npmjs.com/package/@ionic-native/sqlite
And seems like in the last migration of Capacitor 6 of our project it stopped working. So we were wondering if there is still maintenance for this library and where is exactly located in this new repository.

Thank you!

**Comment by marcus-sa** [comment]
@Madserker use https://github.com/capacitor-community/sqlite instead
