### ISSUE TITLE
in-app-browser: error WEBPACK_IMPORTED_MODULE_2__.InAppBrowser.create is not a function

### ISSUE THREAD

**Issue by Homand-Cindy** [danielsogl/awesome-cordova-plugins#4754]
I am using the InAppBrowser plugin in my Ionic/Angular standalone application and when the create function is called, I get this error:
_awesome_cordova_plugins_in_app_browser_ngx__WEBPACK_IMPORTED_MODULE_2__.InAppBrowser.create is not a function

This is my code:

import { InAppBrowser, InAppBrowserObject } from '@awesome-cordova-plugins/in-app-browser/ngx';
let browser: InAppBrowserObject = InAppBrowser.create(url, '_blank', "location=no,clearsessioncache=yes,clearcache=yes");

I've already searched the forums but I can't find another developer who has the same error. Can you help me, please?

**Comment by MaximBelov** [comment]
`
import { InAppBrowser, InAppBrowserObject, InAppBrowserOptions } from '@awesome-cordova-plugins/in-app-browser/ngx';

  private browser: InAppBrowserObject;

  constructor(
    private readonly inAppBrowser: InAppBrowser,
  ) {}
  
    private async openWithInAppBrowser(url: string, config: InAppBrowserOptions) {
       this.browser = this.inAppBrowser.create(url, '_blank', config);
       ....
    }
  
  

`

**Comment by Homand-Cindy** [comment]
Thank you for your response.
It's not possible to add InAppBrowser in the constructor, I have this error:
"InAppBrowser' refers to a value, but is being used as a type here."
I use the version 6.7.0 with cordova-plugin-inappbrowser 6.0.0.

**Comment by Homand-Cindy** [comment]
[package.json](https://github.com/danielsogl/awesome-cordova-plugins/files/15011754/package.json)

**Comment by MaximBelov** [comment]
Maybe the current version does not support the latest angular 17+
I can't check it now; maybe later

Suggestions for now: 
1. Use non-angular version (without ngx)
import { InAppBrowser, InAppBrowserObject } from '@awesome-cordova-plugins/in-app-browser';

2 Do not use @awesome-cordova-plugins/in-app-browser and create service for wrap cordova-plugin-inappbrowser plugin
