### ISSUE TITLE
privacy manifest file missing for cordova

### ISSUE THREAD

**Issue by abineldho** [danielsogl/awesome-cordova-plugins#4846]
ITMS-91061: Missing privacy manifest
 - Your app includes “Frameworks/Cordova.framework/Cordova”, which includes Cordova, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: 
https://developer.apple.com/support/third-party-SDK-requirements
.

**Comment by MaximBelov** [comment]
Hi @abineldho 
Your issue is not related to this repository
Update cordova-ios to the latest version 7.1.0+
See  `privacy-manifest`
https://cordova.apache.org/announcements/2024/04/03/cordova-ios-7.1.0.html
