### ISSUE TITLE
Version 6.10.0 is not available via npm

### ISSUE THREAD

**Issue by EliottSiz** [danielsogl/awesome-cordova-plugins#4868]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report

**Current behavior:**

Hello, I would need to use version 6.10.0 of the plugin but it doesn't seem to be available via npm. Maybe the push to npm failed ? 

```
$ npm view @awesome-cordova-plugins/adjust versions
npm warn Ignoring workspaces for specified package(s)
[
  '5.36.0',        '5.36.1',        '5.37.0',
  '5.37.1',        '5.37.2',        '5.37.3',
  '5.38.0',        '5.39.0',        '5.39.1',
  '5.40.0',        '5.41.0',        '5.42.0',
  '5.43.0',        '5.44.0',        '5.45.0',
  '5.46.0',        '6.0.0-alpha.0', '6.0.0-alpha.1',
  '6.0.0-alpha.2', '6.0.0-alpha.3', '6.0.0-alpha.4',
  '6.0.0',         '6.0.1',         '6.1.0',
  '6.2.0',         '6.3.0',         '6.4.0',
  '6.5.0',         '6.6.0',         '6.7.0',
  '6.8.0',         '6.9.0'
]
```

**Expected behavior:**
Version 6.10.0 is available via npm.

**Comment by pavolsenko** [comment]
I would also need the newest verson. @danielsogl any chance looking into the open merge requests? thanks a lot :)

**Comment by virginmegastore** [comment]
Any update on this issue? when Can we expect version 6.10.0?  --Thanks in advance.

**Comment by Gayathri-Hari-js** [comment]
I would also need it for adjust upgrade to v5.

**Comment by frankpizarro-dev** [comment]
Hello, I would like to ask if there is an estimated release date for version 6.10.0, as we are currently waiting for its release for the adaptation to Adjust v5. Thanks in advance!

**Comment by dev-antonio-xrz231** [comment]
Hello, I would like to ask if there is an estimated release date for version 6.10.0, as we are currently waiting for its release for the adaptation to Adjust v5. Thanks in advance!

**Comment by gxolin** [comment]
6.10.0 skipped, but 6.11.0 available now

```
> npm view @awesome-cordova-plugins/adjust versions
[
  '5.36.0',        '5.36.1',        '5.37.0',
  '5.37.1',        '5.37.2',        '5.37.3',
  '5.38.0',        '5.39.0',        '5.39.1',
  '5.40.0',        '5.41.0',        '5.42.0',
  '5.43.0',        '5.44.0',        '5.45.0',
  '5.46.0',        '6.0.0-alpha.0', '6.0.0-alpha.1',
  '6.0.0-alpha.2', '6.0.0-alpha.3', '6.0.0-alpha.4',
  '6.0.0',         '6.0.1',         '6.1.0',
  '6.2.0',         '6.3.0',         '6.4.0',
  '6.5.0',         '6.6.0',         '6.7.0',
  '6.8.0',         '6.9.0',         '6.11.0'
]

```

**Comment by EliottSiz** [comment]
Thank you, I'll mark this issue as resolved then.

> 6.10.0 skipped, but 6.11.0 available now
> 
> ```
> > npm view @awesome-cordova-plugins/adjust versions
> [
>   '5.36.0',        '5.36.1',        '5.37.0',
>   '5.37.1',        '5.37.2',        '5.37.3',
>   '5.38.0',        '5.39.0',        '5.39.1',
>   '5.40.0',        '5.41.0',        '5.42.0',
>   '5.43.0',        '5.44.0',        '5.45.0',
>   '5.46.0',        '6.0.0-alpha.0', '6.0.0-alpha.1',
>   '6.0.0-alpha.2', '6.0.0-alpha.3', '6.0.0-alpha.4',
>   '6.0.0',         '6.0.1',         '6.1.0',
>   '6.2.0',         '6.3.0',         '6.4.0',
>   '6.5.0',         '6.6.0',         '6.7.0',
>   '6.8.0',         '6.9.0',         '6.11.0'
> ]
> ```
