### ISSUE TITLE
InAppBrowser doesn't work on iOS 18

### ISSUE THREAD

**Issue by Jeremy-Lp** [danielsogl/awesome-cordova-plugins#4875]
**I'm submitting a
- [x] bug report

**Current behavior:**
![image](https://github.com/user-attachments/assets/a1ba8892-ddfd-4ac9-b1d2-457e8a6b1211)
XCode Console:
BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).

**Related code:**
```
const inAppBrowserInstance: InAppBrowserObject = this.ioInAppBrowser.create("https://www.google.com/", "_system");
inAppBrowserInstance.show();
```

In my case I want to open a link "itms-services://" but with "https://www.google.com" it doesn't work either

**Comment by Jeremy-Lp** [comment]
In the repo https://github.dev/apache/cordova-plugin-inappbrowser, the code is up to date:
- (void)openInSystem:(NSURL*)url
{
    [[UIApplication sharedApplication] openURL:url options:@{} completionHandler:^(BOOL success) {
        if (!success) {
            [[NSNotificationCenter defaultCenter] postNotification:[NSNotification notificationWithName:CDVPluginHandleOpenURLNotification object:url]];
        }
    }];
}

Can it be applied here please ?

**Comment by stebbilax** [comment]
I'm running into the same issue, could you share what resolved it for you?

**Comment by Jeremy-Lp** [comment]
@awesome-cordova-plugins/in-app-browser depends on cordova-plugin-inappbrowser, updating the latest package fixed the issue in my case
