### ISSUE TITLE
TODO: ContentSync - Download & Cache Remotely Hosted Content 

### ISSUE THREAD

**Issue by ihadeed** [danielsogl/awesome-cordova-plugins#601]
Reference: https://github.com/phonegap/phonegap-plugin-contentsync

**Comment by vlados** [comment]
Why not use http://ionicframework.com/docs/v2/native/codepush/?

**Comment by ihadeed** [comment]
CodePush is like Ionic Deploy, used to push code updates to your users. ContentSync is different, it lets you download files from a server and cache them for later use. Like how SoundCloud caches the audio, or how SnapChat caches all the pictures and videos.

**Comment by JayRaparla** [comment]
@ihadeed Hi. I am trying to use ContentSync in my ionic 2 application. Were you able to make it work?

**Comment by ihadeed** [comment]
@JayRaparla No set date, but I'll try to include it in the next minor release.
